const baseCommands = [
  'npm install',
  'npm run dev',
]

const finalChecks = [
  'npm run type-check',
  'npm run test:run',
  'npm run build',
]

export default {
  29: {
    start: {
      dir: 'campus-growth-hub',
      commands: [
        'npm install',
        'npm run learner:prepare -- --day 29',
        'npm run test:run -- --passWithNoTests',
        'npm run dev',
      ],
      open: [
        'http://localhost:5173/organizer/activities',
        'src/views/OrganizerActivitiesView.vue',
        'src/api/activity.ts',
        'src/mocks/handlers.ts',
        'src/mocks/activities.ts',
        'src/types/activity.ts',
        'notes/day-29.md',
      ],
      before: [
        '使用 organizer@example.com / organizer123 登录后可进入 /organizer/activities；该路由已指向 src/views/OrganizerActivitiesView.vue。',
        'src/types/activity.ts 已有 id、title、type、startAt、capacity、enrolledCount；今天只补 endAt 和 status，不把 enrolledCount 改名为 enrolled。',
        '唯一数据链路固定为页面 -> src/api/activity.ts -> fetch -> src/mocks/handlers.ts；不得新建 src/services/activity.ts 或第二套 mock。',
        'Day 15-28 已建立 Vitest 与 test:run；learner:prepare 后 test:run 自检成功。',
        '活动修改只要求当前开发会话内可见；浏览器刷新后允许由 MSW fixture 重置，页面和 README 必须明确这是 mock。',
      ],
    },
    tasks: [
      {
        title: '确认表单规则和数据闭环',
        duration: 45,
        files: ['notes/day-29.md', 'src/types/activity.ts', 'src/api/activity.ts', 'src/mocks/handlers.ts'],
        steps: [
          '在 notes/day-29.md 画出列表读取、新增、编辑和状态变更的数据流。',
          '固定必填字段：标题、类型、开始时间、结束时间、人数上限；status 只能是 draft、published、offline。',
          '写明今天只做表格搜索、新增/编辑复用和上下架；删除确认放入选做。',
        ],
        expected: ['学习者能指出每个动作最终修改哪一份活动数据。'],
        tests: [
          '标题为三个空格时无效。',
          'capacity=0 时无效；capacity=1 时有效。',
          'startAt=2026-08-10 10:00、endAt=2026-08-10 09:00 时无效。',
        ],
      },
      {
        title: '完成组织者活动管理 MVP',
        duration: 195,
        files: [
          'src/views/OrganizerActivitiesView.vue',
          'src/components/ActivityFormDrawer.vue',
          'src/api/activity.ts',
          'src/mocks/handlers.ts',
          'src/mocks/activities.ts',
          'src/types/activity.ts',
        ],
        steps: [
          '先显示标题、类型、时间、人数和状态五列，实现标题包含式搜索和 pageSize=6 的简单分页。',
          '再实现 ActivityFormDrawer；新增与编辑使用同一个组件，以 initialValue 是否存在区分模式。',
          '提交前执行跨字段校验；成功后关闭抽屉、显示成功提示并刷新表格。',
          '最后实现 published 与 offline 的切换；操作前显示确认框，确认后才调用 src/api/activity.ts。',
        ],
        expected: [
          '搜索“前端”只显示标题中含“前端”的活动。',
          '新增“Vue 组件工作坊”后表格第一行出现该活动。',
          '编辑标题后列表立即更新且 id 不变。',
          '下架后状态标签显示“已下架”；列表超过 6 条时可以切到第 2 页；刷新后若 fixture 重置，页面仍能重新读取且不报错。',
        ],
        tests: [
          '新增：title=Vue 组件工作坊、type=lecture、startAt=2026-08-10 10:00、endAt=2026-08-10 12:00、capacity=30，预期成功。',
          '错误日期：开始 2026-08-10 10:00、结束 2026-08-10 09:00，预期提示“结束时间必须晚于开始时间”且不调用 service。',
          '取消上下架确认，预期状态不变。',
        ],
      },
      {
        title: '最小栈复现',
        duration: 45,
        files: ['learning-lab/algorithms/day-29-min-stack.ts'],
        steps: ['先画数据栈和最小值栈，再实现 push、pop、top、getMin。'],
        expected: ['能解释为何 getMin 是 O(1)。'],
        tests: ['push(-2), push(0), push(-3), getMin()=-3, pop(), top()=0, getMin()=-2。'],
      },
      {
        title: '回归、提交与记录',
        duration: 75,
        files: ['notes/day-29.md'],
        steps: [...finalChecks, '执行 git diff 并提交 feat: add organizer activity management。'],
        expected: ['三条命令均通过；Console 无未解释错误；记录 AI 辅助等级。'],
        tests: ['重新登录并完整演示搜索、新增、编辑、下架和分页；刷新后能恢复 fixture 且不出现未处理错误。'],
      },
    ],
    optional: ['增加删除确认；只允许删除 draft 活动。', '为表单增加 description 字数提示。'],
    review: {
      route: '/organizer/activities',
      steps: ['登录组织者账号。', '用固定数据新增活动。', '现场把结束时间改早，观察校验。', '取消一次下架，再确认一次下架。'],
      expected: ['新增数据在当前会话可见。', '非法日期不会提交。', '取消确认不改变状态，确认后状态变为 offline。', '刷新后允许重置 fixture，但页面必须正常加载。'],
    },
  },

  30: {
    start: {
      dir: 'campus-growth-hub',
      commands: baseCommands,
      open: [
        'src/views/ActivityListView.vue',
        'src/views/OrganizerActivitiesView.vue',
        'src/composables/usePagination.ts',
        'notes/day-30.md',
      ],
      before: [
        '学生列表与组织者列表都已能分页，但各自重复维护 page、pageSize、pageCount 和越界修正。',
        'Day 29 的组织者管理闭环通过回归；今天重构前先提交或保存干净工作区。',
      ],
    },
    tasks: [
      {
        title: '识别真实重复并设计 usePagination API',
        duration: 60,
        files: ['notes/day-30.md', 'src/views/ActivityListView.vue', 'src/views/OrganizerActivitiesView.vue'],
        steps: [
          '逐行标出两个页面重复的分页状态与越界逻辑。',
          '固定 API：输入 total 和可选 pageSize；输出 page、pageSize、pageCount、setPage、resetPage。',
          '不提取请求逻辑，不创建 useAsyncTask 或 StatusView。',
        ],
        expected: ['notes/day-30.md 中有重构前重复位置和 API 输入输出表。'],
        tests: ['total=21,pageSize=10 时 pageCount=3。', 'total=0 时 pageCount=0，page 保持 1。'],
      },
      {
        title: '提取并接入 usePagination',
        duration: 180,
        files: [
          'src/composables/usePagination.ts',
          'src/views/ActivityListView.vue',
          'src/views/OrganizerActivitiesView.vue',
          'src/composables/__tests__/usePagination.spec.ts',
        ],
        steps: [
          '先写纯分页计算和越界测试，再实现 composable。',
          '先接入学生列表并完成回归，再接入组织者列表。',
          '筛选条件变化时由页面显式调用 resetPage，不把业务筛选塞入 composable。',
        ],
        expected: ['两个页面外观与重构前一致。', '两个页面改 pageSize 后均使用同一套分页逻辑。'],
        tests: [
          'total 从 21 改为 5 且当前 page=3，预期 page 自动回到 1。',
          'setPage(0) 结果为 1；setPage(99) 不超过 pageCount。',
          '在学生页筛选后回到第 1 页，组织者页同样成立。',
        ],
      },
      {
        title: '每日温度挑战',
        duration: 45,
        files: ['learning-lab/algorithms/day-30-daily-temperatures.ts'],
        steps: ['先写暴力解，再在提示后尝试单调栈；不要求完全独立发现。'],
        expected: ['能说明栈中保存下标而不是温度的原因。'],
        tests: ['[73,74,75,71,69,72,76,73] -> [1,1,4,2,1,1,0,0]。'],
      },
      {
        title: '回归、提交与记录',
        duration: 75,
        files: ['notes/day-30.md'],
        steps: [...finalChecks, '提交 refactor: extract shared pagination composable。'],
        expected: ['所有测试通过，两个页面行为无回归。'],
        tests: ['现场将 pageSize 从 10 改为 20，两个页面页数同步按各自总数重算。'],
      },
    ],
    optional: ['为 usePagination 增加 previous 和 next。', '记录为何今天不抽象请求状态。'],
    review: {
      route: '/activities',
      steps: ['演示学生列表分页。', '打开组织者列表演示同一行为。', '现场把一个页面 pageSize 改为 20。'],
      expected: ['两个页面调用同一 composable。', '总数减少时不会停留在不存在的页。', '学习者能解释 composable 与纯工具函数的区别。'],
    },
  },

  31: {
    start: {
      dir: 'campus-growth-hub',
      commands: ['npm install', 'npm install echarts', 'npm run dev'],
      open: [
        'http://localhost:5173/organizer/dashboard',
        'src/router/index.ts',
        'src/views/OrganizerDashboardView.vue',
        'src/components/charts/BaseChart.vue',
        'src/utils/statistics.ts',
        'src/mocks/analytics.ts',
        'notes/day-31.md',
      ],
      before: [
        'Day 23 只建立了组织者活动管理路由；/organizer/dashboard 尚不存在，今天必须创建页面、路由与角色元信息。',
        'Day 29 活动数据可读取；今天使用固定 analytics mock，不接真实后端。',
      ],
    },
    tasks: [
      {
        title: '固定统计口径和数据答案',
        duration: 60,
        files: ['src/mocks/analytics.ts', 'src/utils/statistics.ts', 'src/utils/__tests__/statistics.spec.ts', 'notes/day-31.md'],
        steps: [
          '固定最近 7 天报名数为 [1,2,0,3,4,2,1]。',
          '固定活动类型为 lecture、lecture、contest、volunteer。',
          '固定总报名 13、已确认 8，转化率定义为 confirmed / total，保留 1 位小数。',
          '先在 statistics.spec.ts 写固定答案，再实现纯函数，最后连接图表。',
        ],
        expected: ['总报名=13、已确认=8、转化率=61.5%。', '类型分布为 lecture=2、contest=1、volunteer=1。'],
        tests: ['空数组返回 0 和空分布，不出现 NaN。', 'confirmed=0,total=0 时转化率显示 0%。'],
      },
      {
        title: '完成看板 MVP',
        duration: 180,
        files: ['src/router/index.ts', 'src/views/OrganizerDashboardView.vue', 'src/components/charts/BaseChart.vue', 'src/utils/statistics.ts'],
        steps: [
          '先创建 OrganizerDashboardView.vue，并在 src/router/index.ts 增加 /organizer/dashboard、requiresAuth=true、roles=["organizer"]。',
          '先显示三个统计卡：总报名、已确认、转化率。',
          '再实现最近 7 天报名折线图和活动类型饼图。',
          'BaseChart 在 mounted 初始化，在 resize 时重绘，在 beforeUnmount dispose。',
          '无数据时不创建空图，显示“暂无统计数据”。',
        ],
        expected: ['页面显示 13、8、61.5%。', '折线图有 7 个点，饼图有 3 个分类。', '切换路由再返回不出现重复实例警告。'],
        tests: ['将 mock 切换为空数组，预期统计卡为 0 且显示空状态。', '调整浏览器宽度，图表不溢出容器。'],
      },
      {
        title: '二分查找重做',
        duration: 45,
        files: ['learning-lab/algorithms/day-31-binary-search.ts'],
        steps: ['从空文件限时完成，并写循环不变量。'],
        expected: ['时间复杂度 O(log n)。'],
        tests: ['[-1,0,3,5,9,12],9 -> 4。', '[-1,0,3,5,9,12],2 -> -1。'],
      },
      {
        title: '回归、提交与记录',
        duration: 75,
        files: ['notes/day-31.md'],
        steps: [...finalChecks, '提交 feat: add organizer analytics dashboard。'],
        expected: ['统计纯函数测试通过，构建无 ECharts 生命周期警告。'],
        tests: ['刷新看板、缩放窗口、切换路由、空数据四条路径均通过。'],
      },
    ],
    optional: ['把固定 7 天切换为 14 天；只改数据范围，不增加日期组件。'],
    review: {
      route: '/organizer/dashboard',
      steps: ['核对三个统计卡。', '核对折线图与饼图。', '切成空数据。', '调整窗口并切换路由。'],
      expected: ['固定数值与图表数据一致。', '空数据不报错。', '图表能 resize 且离开页面时销毁。'],
    },
  },

  32: {
    start: {
      dir: 'campus-growth-hub',
      commands: baseCommands,
      open: [
        'src/router/index.ts',
        'src/views/ActivityListView.vue',
        'src/components/ActivityFilters.vue',
        'src/composables/useActivitySearch.ts',
        'src/style.css',
        'notes/day-32.md',
      ],
      before: [
        '学生列表搜索已可用，但每次输入都立即查询。',
        '路由页面仍使用静态 import；Day 31 的 ECharts 页面会进入主包。',
        '今天必做仅为路由懒加载与 300ms 搜索防抖；键盘焦点检查是短回归，不扩展新功能。',
      ],
    },
    tasks: [
      {
        title: '记录优化前证据',
        duration: 60,
        files: ['notes/day-32.md', 'src/router/index.ts', 'src/views/ActivityListView.vue', 'src/composables/useActivitySearch.ts'],
        steps: [
          '运行 npm run build，记录 dist/assets 中最大的 JS 文件名和大小。',
          '在搜索请求入口临时计数，500ms 内输入 v、vu、vue，记录优化前调用次数。',
          '用 Tab 走登录页输入框到提交按钮，记录看不见焦点的位置。',
        ],
        expected: ['notes/day-32.md 有优化前真实数据，不填写主观的“更快了”。'],
        tests: ['连续三次输入的调用次数有明确记录。'],
      },
      {
        title: '完成两项可证明改进',
        duration: 180,
        files: ['src/router/index.ts', 'src/utils/debounce.ts', 'src/views/ActivityListView.vue', 'src/components/ActivityFilters.vue', 'src/composables/useActivitySearch.ts', 'src/style.css'],
        steps: [
          '把页面组件静态 import 改为 () => import(...)；保留路由配置类型。',
          '实现 300ms 防抖，只延迟搜索请求，不延迟输入框文字更新。',
          '在 :focus-visible 中补充可见轮廓，确保登录与报名主流程可见焦点。',
          '再次构建并复测相同输入，将前后证据写入 notes/day-32.md。',
        ],
        expected: ['构建产物出现独立路由 chunk。', '输入 v、vu、vue 后只查询 vue 一次。', '键盘焦点始终可见。'],
        tests: ['输入间隔均小于 300ms，最终请求次数=1、关键词=vue。', '输入 vue 后等待 400ms，再输入 react，预期共请求 2 次。'],
      },
      {
        title: '移动零重做',
        duration: 45,
        files: ['learning-lab/algorithms/day-32-move-zeroes.ts'],
        steps: ['原地完成并说明左右指针含义。'],
        expected: ['不创建第二个同长度数组。'],
        tests: ['[0,1,0,3,12] -> [1,3,12,0,0]。'],
      },
      {
        title: '回归、提交与记录',
        duration: 75,
        files: ['notes/day-32.md'],
        steps: [...finalChecks, '提交 perf: add route splitting and debounced search。'],
        expected: ['有前后证据；不能只写“性能提升”。'],
        tests: ['刷新学生列表、快速搜索、键盘登录、键盘报名均无回归。'],
      },
    ],
    optional: ['压缩一张明显过大的活动封面，并记录实际文件大小变化。'],
    review: {
      route: '/activities',
      steps: ['打开 Network 并清空记录。', '快速输入 v、vu、vue。', '检查最终查询与路由 chunk。', '只用 Tab 和 Enter 完成登录入口操作。'],
      expected: ['只发生一次最终搜索。', '路由 chunk 按访问加载。', '焦点轮廓可见。'],
    },
  },

  33: {
    start: {
      dir: 'campus-growth-hub',
      commands: ['npm install', 'npm run learner:prepare -- --day 33', 'npm run test:run -- --passWithNoTests'],
      open: [
        'package.json',
        'vite.config.ts',
        'src/utils/filterActivities.ts',
        'src/utils/validateEnrollment.ts',
        'src/stores/bookmarks.ts',
        'notes/day-33.md',
      ],
      before: [
        '筛选和报名校验已提取为纯函数；若仍在组件中，今天先做最小提取，不测试组件内部实现。',
        'bookmark store 已能收藏和取消收藏。',
        'Vitest、jsdom、@vue/test-utils、@pinia/testing 以及 test/test:run 脚本已在 Day 29 前建立；今天不重复安装。',
      ],
    },
    tasks: [
      {
        title: '核对 Vitest 配置并跑通第一个业务测试',
        duration: 90,
        files: ['package.json', 'vite.config.ts', 'src/utils/__tests__/filterActivities.spec.ts'],
        steps: [
          '核对 package.json 已有 "test": "vitest" 和 "test:run": "vitest run"，不得新建第二套脚本名。',
          '核对 vite.config.ts 从 vitest/config 导入 defineConfig，并设置 test.environment="jsdom"、test.globals=true。',
          '先写一个 filterActivities 正常用例并执行 npm run test:run。',
        ],
        expected: ['终端显示至少 1 个测试通过。'],
        tests: ['[{title:"Vue 入门",type:"lecture"}], keyword="vue" -> 1 条。'],
      },
      {
        title: '覆盖筛选、报名校验和 store action',
        duration: 180,
        files: [
          'src/utils/__tests__/filterActivities.spec.ts',
          'src/utils/__tests__/validateEnrollment.spec.ts',
          'src/stores/__tests__/bookmarks.spec.ts',
        ],
        steps: [
          '筛选测试覆盖大小写、空关键词和无结果。',
          '报名校验覆盖有效手机号、错误手机号和活动已满。',
          '每个 store 用例前 setActivePinia(createPinia())；覆盖收藏和再次点击取消收藏。',
          '修改一个断言确认测试会失败，再恢复实现或断言。',
        ],
        expected: ['至少 7 个测试通过；失败测试确实能阻止错误规则。'],
        tests: [
          'keyword="VUE" 仍匹配“Vue 入门”；keyword="" 返回全部。',
          'phone=13800138000 且未满 -> valid=true；phone=123 -> valid=false。',
          'capacity=20,enrolledCount=20 -> valid=false，错误含“名额已满”。',
          'toggleBookmark("a1") 两次后收藏列表为空。',
        ],
      },
      {
        title: '有效括号重做',
        duration: 45,
        files: ['learning-lab/algorithms/day-33-valid-parentheses.ts'],
        steps: ['从空文件完成并写出栈中保存的内容。'],
        expected: ['能处理奇数长度和错误闭合顺序。'],
        tests: ['"()[]{}" -> true。', '"([)]" -> false。'],
      },
      {
        title: '测试、构建与提交',
        duration: 45,
        files: ['notes/day-33.md'],
        steps: [...finalChecks, '提交 test: cover filters enrollment and bookmarks。'],
        expected: ['测试、类型检查、构建三项均成功退出。'],
        tests: ['现场将手机号规则改为 11 位数字后，同步修改测试并再次通过。'],
      },
    ],
    optional: ['为 usePagination 增加一个纯逻辑测试。'],
    review: {
      route: '终端与 src/**/__tests__',
      steps: ['运行 npm run test:run。', '随机打开一条测试解释 arrange、act、assert。', '把手机号有效样例改成 123，确认测试失败后恢复。'],
      expected: ['至少 7 个测试通过。', '错误规则会造成红色失败而不是仍然全绿。'],
    },
  },

  34: {
    start: {
      dir: 'campus-growth-hub',
      commands: ['npm ci', 'npm run learner:prepare -- --day 34', ...finalChecks],
      open: ['README.md', 'vercel.json', '.env.example', 'dist/', 'notes/day-34.md'],
      before: [
        'package-lock.json 已提交，因此使用 npm ci 验证干净安装。',
        '默认部署平台固定为 Vercel；项目使用 history 路由。开始前确认有可登录的 Vercel 账号和可用网络。',
        '若账号或网络不可用，Day 34 与 Day 35 统一采用本地 npm run preview 作为降级验收，不把公网 URL 作为通过门槛。',
        '所有业务数据均为 mock/localStorage，README 必须明确这不是后端鉴权和真实持久化。',
      ],
    },
    tasks: [
      {
        title: '验证可重复安装和本地生产版本',
        duration: 60,
        files: ['README.md', '.env.example', 'package-lock.json'],
        steps: [
          '按 npm ci、type-check、test:run、build 顺序执行并记录结果。',
          '在单独终端运行 npm run preview -- --host 127.0.0.1，记录地址；回归完成后按 Ctrl+C 停止，不占用后续部署终端。',
          'README 写明 Node 版本、安装、开发、测试、构建、预览命令及两类演示账号。',
        ],
        expected: ['不了解仓库的人只看 README 可以启动项目。'],
        tests: ['缺少 .env.local 时仍能使用默认 mock；若不能，README 必须写明复制 .env.example 的步骤。'],
      },
      {
        title: '部署到 Vercel',
        duration: 120,
        files: ['vercel.json', 'README.md', 'docs/screenshots/'],
        steps: [
          '创建 vercel.json，使用 SPA fallback 把非静态文件路由重写到 /index.html。',
          '执行 npx vercel --prod，并把最终 https URL 写入 README。',
          '保存学生列表、报名成功、组织者管理、看板四张截图。',
        ],
        expected: ['公网 URL 可访问；直接打开深链接不会 404。'],
        tests: ['直接打开 /activities/a1。', '刷新 /organizer/dashboard。', '访问 /activities/not-found。'],
      },
      {
        title: '生产回归与一次路径故障演练',
        duration: 105,
        files: ['vercel.json', 'notes/day-34.md'],
        steps: [
          '按学生登录、搜索、详情、收藏、报名、个人中心完整回归。',
          '按组织者登录、新增、编辑、下架、看板完整回归。',
          '由 learner:prepare 创建 practice/day-34/deploy-fault/vercel.json 临时副本；只在该副本中移除 SPA rewrite 并记录差异，不直接破坏根目录 vercel.json。',
          '记录复现、证据、原因和修复，不在主分支保留错误配置。',
        ],
        expected: ['生产版两条闭环通过；故障能够稳定复现并恢复。'],
        tests: ['Console 无未解释错误。', '退出登录后受限路由回到登录页。'],
      },
      {
        title: '旧算法与发布记录',
        duration: 75,
        files: ['learning-lab/algorithms/day-34-review.ts', 'notes/day-34.md'],
        steps: ['固定重做 LeetCode 155 和 739，各最多 25 分钟。', '提交 chore: prepare reproducible project release。'],
        expected: ['有部署 URL、命令日志、故障记录和两题复杂度。'],
        tests: ['最小栈固定序列通过。', '每日温度固定样例通过。'],
      },
    ],
    optional: ['若 Vercel 因网络或账号不可用，保留成功的本地 preview 和完整部署日志，不临时切换多个平台；这仍可判定 Day 34 通过。'],
    review: {
      route: 'README 中的生产 URL；无账号/网络时使用本地 preview URL',
      steps: ['从无登录状态打开已记录 URL。', '直接打开 /activities/a1 并刷新。', '演示两类账号。', '说明一次 404 的复现与修复。'],
      expected: ['使用 Vercel 时深链接不 404；使用本地 fallback 时说明尚未验证线上 rewrite。', 'README 命令可复制执行。', '清楚说明 mock 与真实后端的边界。'],
    },
  },

  35: {
    start: {
      dir: 'campus-growth-hub',
      commands: ['npm install', ...finalChecks],
      open: ['README.md', 'docs/architecture.md', 'docs/demo-script.md', 'docs/known-issues.md', 'docs/ai-usage.md', 'notes/day-35.md'],
      before: [
        'Day 34 已留下可访问的生产 URL；若因账号/网络降级，则留下本地 preview URL 和完整阻塞记录。测试、类型检查和构建均通过。',
        '今天冻结功能，只修复阻塞固定演示脚本的问题。',
      ],
    },
    tasks: [
      {
        title: '整理本周证据与阻塞项',
        duration: 30,
        files: ['notes/day-35.md', 'docs/known-issues.md', 'docs/ai-usage.md'],
        steps: ['只选一个最影响演示的 D/E 项；其余写入 known-issues。', '写出本周三个已掌握证据。'],
        expected: ['今天只有一个允许修复的阻塞项。'],
        tests: ['阻塞项必须能用固定操作步骤复现。'],
      },
      {
        title: '按固定脚本终验项目',
        duration: 60,
        files: ['docs/demo-script.md', 'docs/architecture.md'],
        steps: [
          '依次演示：学生登录、搜索、详情、收藏、报名、个人中心。',
          '再演示：组织者登录、新增、编辑、下架、看板。',
          '在 architecture.md 画出页面 -> store/service -> mock/localStorage 数据流。',
        ],
        expected: ['12 个步骤均从用户入口开始；架构图能对应到真实文件。'],
        tests: ['每一步写明预期页面文字或状态；任何失败都登记而不是跳过。'],
      },
      {
        title: '无 AI 完成一个规则修改',
        duration: 30,
        files: ['src/utils/validateEnrollment.ts', 'src/utils/__tests__/validateEnrollment.spec.ts'],
        steps: ['把报名手机号规则改为必须是 11 位数字，并同步更新测试。'],
        expected: ['先看到旧测试失败，再更新规则与测试全部通过。'],
        tests: ['13800138000 有效；123 和 1380013800 无效。'],
      },
      {
        title: '冻结版本并打标签',
        duration: 30,
        files: ['README.md', 'docs/architecture.md', 'docs/demo-script.md', 'docs/known-issues.md', 'docs/ai-usage.md'],
        steps: ['执行 git status，提交 docs: finalize project evidence。', '执行 git tag -a v0.1.0 -m "campus growth hub demo"。', '执行 git show v0.1.0 --stat 确认标签指向最终提交。'],
        expected: ['工作区干净；v0.1.0 存在；项目不再追加新功能。'],
        tests: ['npm run test:run、npm run type-check、npm run build 全部通过。'],
      },
    ],
    optional: ['无。今天剩余时间用于休息，不补做非阻塞功能。'],
    review: {
      route: '生产 URL或本地 preview URL 与 docs/demo-script.md',
      steps: ['按固定 12 步抽查学生端和组织者端。', '随机打开一个关键文件画数据流。', '检查 v0.1.0 标签。'],
      expected: ['演示可重复。', '能讲一个真实取舍和一次真实排错。', '只修阻塞问题，没有临时扩展范围。'],
    },
  },

  36: {
    start: {
      dir: 'campus-growth-hub',
      commands: baseCommands,
      open: ['public/mock/http-demo.json', 'src/api/request.ts', 'src/mocks/handlers.ts', 'src/stores/auth.ts', 'docs/web-fundamentals.md', 'notes/day-36.md'],
      before: [
        '主项目唯一请求方案是 fetch + MSW；不得新建 src/services/request.ts 或第二套 mock。',
        '今天用 fetch("/mock/http-demo.json") 观察静态真实 GET，同时用 MSW handler 的 scenario 参数演练业务错误。',
        '前端角色守卫不等于后端鉴权，文档必须明确。',
      ],
    },
    tasks: [
      {
        title: '建立 HTTP 与浏览器主线',
        duration: 105,
        files: ['public/mock/http-demo.json', 'docs/web-fundamentals.md'],
        steps: [
          '创建固定 JSON：{"message":"network-ok","version":1}，在页面或 Console 使用 fetch 读取。',
          '在 Network 记录 URL、method、status、request headers、response headers、initiator 和 timing。',
          '回答六题：URL 到页面主线；GET/POST；200/401/404/500；强缓存/协商缓存；CORS；Cookie 与 token。',
        ],
        expected: ['Network 中可见 GET /mock/http-demo.json 且 status=200。', '六题每题 3-5 句并绑定一个项目例子。'],
        tests: ['访问不存在的 /mock/missing.json，预期 404。', '重复请求并说明 DevTools 中实际缓存现象，不编造响应头。'],
      },
      {
        title: '完成安全边界说明与一个可验证修正',
        duration: 135,
        files: ['src/stores/auth.ts', 'src/api/request.ts', 'src/mocks/handlers.ts', 'docs/web-fundamentals.md'],
        steps: [
          '检查 localStorage 内容；确认不保存密码，只保存演示所需最小会话字段。',
          '退出登录时清除 token、role 和 user，并跳转登录页。',
          '在 src/mocks/handlers.ts 为仅开发使用的 scenario=401 和 scenario=500 返回固定状态；src/api/request.ts 只负责把状态转成统一错误。',
          '文档回答 XSS 与 CSRF 的攻击目标、常见前提和基本防护，不声称当前 mock 项目已实现后端安全。',
        ],
        expected: ['退出后 localStorage 无会话字段。', 'scenario=401 时页面显示登录失效并回登录页；scenario=500 时显示可重试错误。'],
        tests: ['密码字段从未写入 localStorage。', '401 与 500 的 UI 行为不同。'],
      },
      {
        title: '环形链表重做',
        duration: 45,
        files: ['learning-lab/algorithms/day-36-linked-list-cycle.ts'],
        steps: ['画快慢指针相遇过程后编码。'],
        expected: ['时间 O(n)、空间 O(1)。'],
        tests: ['[3,2,0,-4], pos=1 -> true。', '[1], pos=-1 -> false。'],
      },
      {
        title: '回归、提交与记录',
        duration: 75,
        files: ['docs/web-fundamentals.md', 'notes/day-36.md'],
        steps: [...finalChecks, '提交 docs: connect web fundamentals to project。'],
        expected: ['文档能区分真实 Network 证据、mock 行为和真实后端职责。'],
        tests: ['现场切换 200、401、500，准确解释页面应有行为。'],
      },
    ],
    optional: ['补充 SameSite、HttpOnly、Secure 的用途，但不改造为真实 Cookie 登录。'],
    review: {
      route: '/activities 与 DevTools Network',
      steps: ['观察固定 JSON 请求。', '访问 404 资源。', '切换 mock 401 与 500。', '退出登录后检查 localStorage。'],
      expected: ['能从 Network 找到状态码和响应。', '401、500、退出登录行为符合规格。', '能说明 CORS 在浏览器侧触发但由服务端响应头决定是否放行。'],
    },
  },

  37: {
    start: {
      dir: 'campus-growth-hub',
      commands: ['npm install', 'npm run learner:prepare -- --day 37', 'npm run type-check', 'npm run dev'],
      open: ['practice/day-37/README.md', 'practice/day-37/debounce.ts', 'practice/day-37/promise-error.ts', 'practice/day-37/cases.spec.ts', 'docs/frontend-core-examples.md', 'notes/day-37.md'],
      before: [
        'learner:prepare 已生成 practice/day-37 starter 和可被项目 Vitest 扫描的 cases.spec.ts；不要手工发明测试框架。',
        '今天必做理论只含闭包、事件循环、Vue 响应式和 Pinia 状态边界。',
        '必做手写只含防抖与 Promise 错误处理；数组去重和 composable 放入选做。',
        '项目中没有自然例子时写“未找到”，禁止为了闭包等术语强行改代码。',
      ],
    },
    tasks: [
      {
        title: '四个核心概念短答',
        duration: 75,
        files: ['docs/frontend-core-examples.md'],
        steps: ['每个概念写定义、最小例子、项目证据或“未找到”、一个常见误区。'],
        expected: ['每个回答可在 90 秒内口述，不背长文。'],
        tests: ['事件循环例子 Promise.then 先于 setTimeout。', 'Pinia 与页面局部筛选状态边界解释正确。'],
      },
      {
        title: '无 AI 手写防抖与 Promise 错误处理',
        duration: 150,
        files: ['practice/day-37/debounce.ts', 'practice/day-37/promise-error.ts', 'practice/day-37/cases.spec.ts'],
        steps: [
          '实现 debounce(fn, wait)，保留调用时 this 与参数。',
          '实现 runTask(task)，返回成功数据；失败时返回可显示的错误；finally 中结束 loading。',
          '先写固定测试，再编码；最多请求一次提示。',
          '实现后运行 npm run test:run -- practice/day-37/cases.spec.ts。',
        ],
        expected: ['快速三次调用只执行最后一次。', 'Promise reject 后 loading=false 且错误可读取。'],
        tests: ['wait=100，0/30/60ms 调用参数 a/b/c，160ms 后只得到 c。', 'task resolve("ok") -> data="ok"。', 'task reject(new Error("boom")) -> error="boom", loading=false。'],
      },
      {
        title: '项目证据走查',
        duration: 60,
        files: ['docs/frontend-core-examples.md'],
        steps: ['固定查找异步、响应式和状态管理各一个例子，记录准确文件和函数名。', '闭包若无可信例子，只使用 debounce 练习例子。'],
        expected: ['每个说法都能打开实际代码核对。'],
        tests: ['学习者随机选择一个证据，并说明输入、状态变化和 UI 结果。'],
      },
      {
        title: '反转链表与提交',
        duration: 75,
        files: ['learning-lab/algorithms/day-37-reverse-list.ts', 'notes/day-37.md'],
        steps: ['用 30 分钟重做反转链表。', '运行 npm run test:run -- practice/day-37/cases.spec.ts 和 npm run type-check。', '提交 docs: add frontend core explanations。'],
        expected: ['四概念、两手写、一算法均有固定证据。'],
        tests: ['[1,2,3,4,5] -> [5,4,3,2,1]。'],
      },
    ],
    optional: ['手写数组去重并比较 Set 与循环。', '从空文件重写 usePagination 的最小版本。'],
    review: {
      route: 'docs/frontend-core-examples.md 与 practice/day-37',
      steps: ['随机口述两个概念。', '运行防抖固定测试。', '把 wait 从 100 改为 200 并调整断言。', '打开一个项目证据核对。'],
      expected: ['回答有代码依据。', '防抖参数化后仍通过。', '不会为了显得完整而虚构项目例子。'],
    },
  },

  38: {
    start: {
      dir: 'campus-growth-hub',
      commands: ['npm install', 'npm run learner:prepare -- --day 38', 'npm run type-check', 'npm run dev'],
      open: ['docs/project-walkthrough.md', 'practice/day-38/faults/README.md', 'practice/day-38/faults/router-guard.ts', 'practice/day-38/faults/router-guard.spec.ts', 'practice/day-38/faults/race-search.ts', 'practice/day-38/faults/race-search.spec.ts', 'practice/day-38/faults/bookmark-store.ts', 'notes/day-38.md'],
      before: [
        'learner:prepare 已生成 practice/day-38/faults 的故障 starter、README 与失败测试；学习者不得自己发明故障。',
        '故障练习全部位于 practice/day-38/faults，不直接破坏 v0.1.0 演示版本。',
        '必做故障为路由权限和请求竞态；store 不同步为选做。',
        'router-guard.ts 的故障行为：未登录访问 requiresAuth 页面仍返回 true。',
        'race-search.ts 的固定延迟：关键词 v=800ms、vue=100ms，旧结果会覆盖新结果。',
        'bookmark-store.ts 的故障行为：详情页改局部 ref，个人中心读取 Pinia，导致跨页不同步。',
      ],
    },
    tasks: [
      {
        title: '准备可核对的项目表达',
        duration: 75,
        files: ['docs/project-walkthrough.md'],
        steps: [
          '按背景、用户、本人完成、技术选型、数据流、一个难点、一个取舍、一个遗留问题写提纲。',
          '录制或计时完成 3 分钟概览和 8 分钟代码深讲。',
          '每个技术亮点附真实文件路径，不使用“提升了很多性能”等无证据表述。',
        ],
        expected: ['3 分钟概览不超时；8 分钟深讲能打开至少三个真实文件。'],
        tests: ['学习者录下自己回答“为何不用后端”，回答能说明 40 天范围和 mock 边界。'],
      },
      {
        title: '修复两个固定故障',
        duration: 180,
        files: ['practice/day-38/faults/router-guard.ts', 'practice/day-38/faults/router-guard.spec.ts', 'practice/day-38/faults/race-search.ts', 'practice/day-38/faults/race-search.spec.ts', 'practice/day-38/faults/README.md'],
        steps: [
          '每题严格按复现 -> Console/日志证据 -> 一个假设 -> 单点修改 -> 回归记录。',
          '路由题只允许查看 router-guard.ts；目标是未登录重定向 /login，已登录继续。',
          '竞态题只允许查看 race-search.ts；目标是只接收最新请求或取消旧请求。',
          '每次只运行对应 spec；修复后保留故障原因说明和最小测试，不把错误代码合入 src。',
          '两题结束后运行 npm run test:run -- practice/day-38/faults，必须全部通过。',
        ],
        expected: ['未登录不再进入受限页。', '快速请求 v 后请求 vue，最终结果始终是 vue。'],
        tests: ['token=""、requiresAuth=true -> /login。', 'token="demo"、requiresAuth=true -> true。', 'v(800ms) 后 50ms 发 vue(100ms)，最终 renderedKeyword="vue"。'],
      },
      {
        title: '二叉树最大深度重做',
        duration: 45,
        files: ['learning-lab/algorithms/day-38-max-depth.ts'],
        steps: ['先画递归终止条件，再编码。'],
        expected: ['空树返回 0。'],
        tests: ['[3,9,20,null,null,15,7] -> 3。'],
      },
      {
        title: '回归与记录',
        duration: 60,
        files: ['docs/project-walkthrough.md', 'notes/day-38.md'],
        steps: [...finalChecks, '提交 docs: add project walkthrough and fault evidence。'],
        expected: ['正式项目仍通过全部检查；两个练习故障都有证据链。'],
        tests: ['演示 v0.1.0 生产路径未被故障练习影响。'],
      },
    ],
    optional: ['完成 bookmark-store.ts：详情收藏后个人中心必须立即一致，并说明为何状态应进入 Pinia。'],
    review: {
      route: 'docs/project-walkthrough.md 与 practice/day-38/faults',
      steps: ['做 3 分钟项目概览。', '检查者指定一个技术点并打开代码。', '随机复现路由或竞态故障并要求说明排查证据。'],
      expected: ['表达与代码一致。', '能先复现再修改。', '两个必做故障测试通过且正式项目无回归。'],
    },
  },

  39: {
    start: {
      dir: 'campus-growth-hub',
      commands: ['npm install', 'npm run learner:prepare -- --day 39', 'npm run type-check'],
      open: ['practice/day-39/interview-pack.md', 'practice/day-39/code-reading.ts', 'practice/day-39/debounce.ts', 'practice/day-39/day-39.spec.ts', 'practice/day-39/checker-answer-key.md', 'notes/day-39-interview-score.md'],
      before: [
        'learner:prepare 已生成完整代码阅读 starter、失败测试、固定题包和 checker-answer-key.md；学习过程中不得打开答案卡，只在当天全部任务结束后的统一审查中使用。',
        '今天不随机选题；固定算法为 LeetCode 1 两数之和与 LeetCode 20 有效括号。',
        '固定手写为 debounce(fn, wait)。',
        '固定代码阅读文件包含异步循环陷阱：forEach(async item => await save(item)) 后立即打印 done。',
        '模拟期间关闭 AI 和项目笔记；可询问澄清但不能获得提示。',
      ],
    },
    tasks: [
      {
        title: '准备题包与评分规则',
        duration: 60,
        files: ['practice/day-39/interview-pack.md', 'practice/day-39/checker-answer-key.md', 'notes/day-39-interview-score.md'],
        steps: [
          '检查 learner:prepare 生成的题包固定八问：闭包；事件循环；ref/computed/watch；props/emit；Pinia 状态边界；HTTP 缓存；项目数据流；一次真实排错。',
          '检查答案卡已有参考要点，评分维度固定为理解、表达、正确性、边界、提示次数，各 0-2 分。',
          '确认 75 分钟模拟分配：算法 25、代码阅读 10、手写 15、基础问答 15、项目追问 10；学习者不改题。',
        ],
        expected: ['固定题包无需任何人临时出题即可开始。'],
        tests: ['题目和评分表完整，答案区只在当天结束统一审查时打开。'],
      },
      {
        title: '完成固定 75 分钟模拟技术面',
        duration: 75,
        files: ['practice/day-39/code-reading.ts', 'practice/day-39/debounce.ts', 'practice/day-39/day-39.spec.ts', 'notes/day-39-interview-score.md'],
        steps: [
          '两数之和只要求哈希方案；有效括号使用栈。',
          '代码阅读题解释为何 done 先打印，并给出 for...of 顺序等待或 Promise.all 并发方案。',
          '手写 debounce 并用固定三次调用验证。',
          '按题包中标记的固定四问作答，再完成一个项目数据流追问；全程录音或逐字记录，不在中途查看答案卡。',
          '模拟结束后运行 npm run test:run -- practice/day-39/day-39.spec.ts；测试结果计入原始分，不在模拟计时中偷偷修正。',
        ],
        expected: ['全程记录卡住位置、澄清次数和实际得分。'],
        tests: ['twoSum([2,7,11,15],9) -> [0,1]。', 'isValid("([)]") -> false。', '0/30/60ms 调用 debounce，wait=100，最终只执行第三次。'],
      },
      {
        title: '只修最高优先级漏洞',
        duration: 120,
        files: ['notes/day-39-interview-score.md'],
        steps: [
          '按影响排序，只选择得分最低且大厂前端高频的一项。',
          '先重做原题，再做一个同类变式；不得同时补四个主题。',
          '记录第一次错误、修正依据和第二次是否独立。',
        ],
        expected: ['只有一个漏洞进入补强，且有前后对照。'],
        tests: ['若补算法，必须换一组输入；若补问答，必须用项目例子重新回答。'],
      },
      {
        title: '项目问答复现与最终记录',
        duration: 105,
        files: ['docs/project-walkthrough.md', 'notes/day-39-interview-score.md'],
        steps: ['重做模拟中未通过的项目追问。', '运行 npm run type-check、npm run test:run、npm run build。', '提交 docs: record fixed mock interview results。'],
        expected: ['评分表包含原始分、补强后分、下一阶段问题，不修改原始成绩。'],
        tests: ['评分表能复现题目、学习者回答和给分理由。'],
      },
    ],
    optional: ['无。不要用额外题量掩盖模拟中暴露的问题。'],
    review: {
      route: 'notes/day-39-interview-score.md',
      steps: ['核对 75 分钟原始记录。', '重问最低分问题。', '将一道算法输入改为 [3,3], target=6 或将括号输入改为 "(("。'],
      expected: ['学习者能说明卡住时如何沟通。', '复杂度与边界判断正确。', '原始成绩保留，没有事后美化。'],
    },
  },

  40: {
    start: {
      dir: 'campus-growth-hub',
      commands: ['npm install', 'npm run learner:prepare -- --day 40', 'npm run type-check'],
      open: ['practice/day-40/baseline-day-01.md', 'practice/day-40/final-assessment/README.md', 'practice/day-40/final-assessment/activities.ts', 'practice/day-40/final-assessment/ActivityPanel.vue', 'practice/day-40/final-assessment/assessment.spec.ts', 'docs/final-assessment.md'],
      before: [
        'learner:prepare 已把 Day 1 基线复制为 practice/day-40/baseline-day-01.md，并生成固定数据、空组件、预设错误与失败测试。',
        '最终题使用项目内的 practice/day-40/final-assessment，不在完整主项目中找现成功能。',
        '90 分钟内禁止 AI、旧项目代码和教程；允许查看 Vue API 官方文档，但要记录查阅项。',
        '使用与 Day 1 相同维度：正确性、独立性、提示次数、耗时、解释与排错。',
        '固定数据为五条活动：a1 Vue 入门/lecture/20/18，a2 篮球赛/contest/10/10，a3 志愿服务/volunteer/30/12，a4 前端沙龙/lecture/25/5，a5 算法训练/contest/40/39。字段依次为 id/title/type/capacity/enrolledCount。',
      ],
    },
    tasks: [
      {
        title: '确认规则并保存起始证据',
        duration: 30,
        files: ['practice/day-40/final-assessment/README.md', 'practice/day-40/final-assessment/assessment.spec.ts', 'docs/final-assessment.md'],
        steps: ['记录开始时间、允许工具和 git diff。', '只读需求与测试，不预先查看主项目相似实现。'],
        expected: ['起始文件只含固定数据、空组件和失败测试。'],
        tests: ['开始前运行最终题测试，应因功能未实现而失败。'],
      },
      {
        title: '90 分钟无 AI 综合对照题',
        duration: 90,
        files: ['practice/day-40/final-assessment/activities.ts', 'practice/day-40/final-assessment/ActivityPanel.vue', 'practice/day-40/final-assessment/assessment.spec.ts'],
        steps: [
          '实现按 type 筛选、按标题关键词搜索、剩余名额 capacity-enrolledCount、根据 id 查找活动。',
          '在 Vue 组件中接入关键词输入、类型下拉、重置按钮、结果数量和空状态。',
          '点击活动切换收藏；收藏数实时显示。',
          '修复预设错误：模板使用 remainCount，但脚本导出名为 remainingCount。',
          '完成后运行 npm run test:run -- practice/day-40/final-assessment/assessment.spec.ts。',
          '到 90 分钟立即停止，保留未完成代码。',
        ],
        expected: ['lecture 筛选得到 a1、a4。', '关键词“前端”得到 a4。', 'contest 且仅看有名额得到 a5。', '无结果显示“没有符合条件的活动”。', '点击 a1 两次后收藏数回到 0。'],
        tests: [
          'remaining(a1)=2；remaining(a2)=0。',
          'findById("missing")=undefined。',
          'keyword="vue" 大小写不敏感匹配 a1。',
          '重置后关键词为空、类型为 all、结果数为 5。',
        ],
      },
      {
        title: '最终项目发布检查与证据归档',
        duration: 90,
        files: ['docs/architecture.md', 'docs/project-evidence.md', 'docs/screenshots/', 'README.md'],
        steps: ['按 Day 35 固定脚本演示学生端与组织者端。', ...finalChecks, '核对生产 URL、v0.1.0 标签、架构图、截图、known issues。'],
        expected: ['最终项目可构建、可测试、可部署、可按脚本演示。'],
        tests: ['学生闭环和组织者闭环均通过；生产深链接刷新正常。'],
      },
      {
        title: '固定两道算法终验',
        duration: 60,
        files: ['learning-lab/algorithms/day-40-two-sum.ts', 'learning-lab/algorithms/day-40-valid-parentheses.ts'],
        steps: ['无 AI 完成 LeetCode 1 哈希解和 LeetCode 20 栈解，各最多 25 分钟。', '写复杂度和一个失败输入。'],
        expected: ['两数之和 O(n)，有效括号 O(n)。'],
        tests: ['[2,7,11,15],9 -> [0,1]。', '"{[]}" -> true；"([)]" -> false。'],
      },
      {
        title: '对照 Day 1 并形成下一阶段交接',
        duration: 60,
        files: ['practice/day-40/baseline-day-01.md', 'docs/final-assessment.md', 'docs/next-14-days.md'],
        steps: ['逐项比较 Day 1 与 Day 40 的独立完成比例、提示次数和耗时。', '保留未完成项，不把部分通过写成掌握。', '下一阶段只列三个最高优先级：投递材料、面试弱项、项目遗留问题。'],
        expected: ['结论由数据支持，不使用“进步很大”替代证据。'],
        tests: ['每个能力结论都引用 Day 1 和 Day 40 的具体记录。'],
      },
      {
        title: '最终提交',
        duration: 30,
        files: ['docs/final-assessment.md', 'docs/next-14-days.md'],
        steps: ['执行 git diff，提交 chore: complete forty-day final assessment。', '执行 git status 确认无遗漏。'],
        expected: ['最终提交聚焦且所有证据可追溯。'],
        tests: ['重新运行测试、类型检查和构建，结果全部成功。'],
      },
    ],
    optional: ['无。终验日不临时美化页面、不增加新功能。'],
    review: {
      route: 'practice/day-40/final-assessment 与生产 URL或本地 preview URL',
      steps: ['核对 90 分钟结束时间、工具记录和已经保存的测试/构建结果。', '现场把筛选增加 availableOnly 条件并只运行最终题定向测试。', '抽查一条项目演示路径。', '对照 Day 1 的一项评分证据。'],
      expected: ['固定测试全部通过或如实保留未完成。', '现场修改能贯通数据与页面。', 'Day 1/Day 40 对照可量化。', '不在 30 分钟验收中重复执行完整构建。'],
    },
  },
}
