export default {
  15: {
    start: {
      dir: "campus-growth-hub",
      commands: [
        "npm install -D typescript vue-tsc vitest jsdom",
        "npm pkg set scripts.type-check=\"vue-tsc --noEmit\" scripts.test:run=\"vitest run\"",
        "git status",
      ],
      open: ["package.json", "index.html", "src/main.js 或 src/main.ts", "src/views/HomeView.vue", "src/data/activities.js", "src/components/ActivityCard.vue"],
      before: [
        "从 Day 14 的提交开始，首页筛选、收藏、空态和错误重试均可运行。",
        "先确认当前项目：存在 src/main.js 表示 JS 项目；存在 src/main.ts 表示已是 TS 项目，两者只能有一个。",
        "保存一次迁移前提交；禁止重新创建 Vite 项目或覆盖已有 src。",
      ],
    },
    tasks: [
      {
        title: "把现有 Vue 项目安全切入 TypeScript",
        duration: 90,
        files: ["package.json", "index.html", "tsconfig.json", "src/main.ts", "src/vite-env.d.ts", "src/views/HomeView.vue"],
        steps: [
          "若当前是 JS 项目，把 src/main.js 重命名为 src/main.ts，并把 index.html 的 /src/main.js 同步改为 /src/main.ts；若已是 TS 项目，只核对入口，不重复迁移。",
          "创建单一 tsconfig.json：compilerOptions 固定为 target ES2020、module ESNext、moduleResolution Bundler、lib ES2020/DOM/DOM.Iterable、strict true、skipLibCheck true、isolatedModules true、resolveJsonModule true、esModuleInterop true、jsx preserve、noEmit true；include 固定为 src/**/*.ts、src/**/*.tsx、src/**/*.vue。今天不创建 tsconfig.app.json 或项目引用。",
          "创建 src/vite-env.d.ts，内容只有 /// <reference types=\"vite/client\" />。",
          "把当天会改动的 Vue 组件 script 改为 <script setup lang=\"ts\">；其余组件暂不批量改造。",
          "运行 npm run type-check，逐条修复迁移本身造成的错误；不得使用 // @ts-ignore 或 as any 消音。",
          "运行 npm run dev，确认首页行为与 Day 14 相同。",
        ],
        expected: ["首页可正常打开，筛选和收藏仍工作。", "npm run type-check 首次可执行，最终零错误。"],
        tests: ["npm run type-check", "npm run build", "浏览器打开 /，执行一次筛选和收藏"],
      },
      {
        title: "建立活动与接口结果的最小类型",
        duration: 110,
        files: ["src/types/activity.ts", "src/types/api.ts", "src/mocks/activities.ts", "src/utils/activity.ts", "src/utils/activity.test.ts", "src/views/HomeView.vue", "src/data/activities.js"],
        steps: [
          "定义 Activity：id/title/type/startAt/capacity/enrolledCount；id、title、type、startAt 为 string，人数为 number。",
          "定义 ApiResult<T>：code 为 number、message 为 string、data 为 T。",
          "写入 fixture：a001 容量 30 已报名 12；a002 容量 20 已报名 20，后续用它验证已满。",
          "把 src/data/activities.js 的既有数据迁入 src/mocks/activities.ts，保留原 id 和页面内容；随后更新 HomeView.vue 导入并删除旧 JS 导入，禁止保留两份活动源。",
          "在 src/utils/activity.ts 写 getRemaining(activity): number 与 unwrap(result: unknown): T；unwrap 先做最小对象、code 和 data 检查。",
          "在 src/utils/activity.test.ts 用 Vitest 写 a001 剩余 18、a002 剩余 0、非法 ApiResult 抛错三个测试。",
          "依次制造并记录 5 个错误：capacity 写成字符串、漏 title、函数参数传 null、函数声明返回 string 却返回 number、直接读取 unknown.data；每次保存错误文本后修复。",
        ],
        expected: ["fixture 能被首页导入，画面内容不变。", "5 个错误都有“错误位置—含义—修复”记录。"],
        tests: ["npm run type-check", "npm run test:run -- src/utils/activity.test.ts", "把 a001.capacity 临时改为字符串时必须报错，恢复数字后通过"],
      },
      {
        title: "将 Activity 类型接入一条真实组件链路",
        duration: 120,
        files: ["src/views/HomeView.vue", "src/components/ActivityCard.vue", "src/mocks/activities.ts"],
        steps: [
          "只改 HomeView → ActivityCard 这一条真实链路：HomeView 活动列表标注为 Activity[]，卡片 prop 标注为 Activity。",
          "页面显示 title、type、剩余名额；剩余为 0 时显示“已满”。",
          "删除一次 getRemaining 实现，在不看旧代码的情况下重写。",
          "观察编辑器类型提示：输入 activity. 后能看到字段；输入 activity.foo 应立即报错。",
        ],
        expected: ["a001 显示剩余 18，a002 显示已满。", "页面无红屏，Console 无错误。"],
        tests: ["npm run type-check", "npm run test:run", "npm run build", "临时写 activity.foo 能触发类型错误，随后删除"],
      },
      {
        title: "算法与当日留痕",
        duration: 40,
        files: ["notes/day-15.md", "algorithms/day15-queue.ts", "algorithms/day15-queue.test.ts"],
        steps: ["完成 LeetCode 232；先画两个栈的状态，再写 push/pop/peek/empty。", "在 day15-queue.test.ts 写题目示例与空队列用例并运行指定 Vitest。", "记录复杂度、空队列边界与 AI 等级，提交 refactor: introduce core activity types。"],
        expected: ["能解释为什么元素只在必要时从输入栈搬到输出栈。"],
        tests: ["npm run test:run -- algorithms/day15-queue.test.ts", "依次 push 1、push 2、peek 得 1、pop 得 1、empty 得 false"],
      },
    ],
    optional: ["为 Activity.type 收窄成 'tech' | 'sports' | 'volunteer'，不扩展泛型工具类型。"],
    review: {
      route: "/",
      steps: ["启动项目并演示 a001/a002。", "运行 npm run type-check。", "把 a001 新增 capacity 字段的错误改成给 capacity 传字符串，要求学习者定位并修复。"],
      expected: ["页面与迁移前一致。", "学习者能说明类型推断、unknown 与 any 的差异，并在 5 分钟内修复类型错误。"],
    },
  },

  16: {
    start: {
      dir: "campus-growth-hub",
      commands: ["git status", "npm run type-check", "npm run test:run"],
      open: ["src/types/activity.ts", "src/types/api.ts", "src/mocks/activities.ts", "src/App.vue"],
      before: ["Day 15 类型迁移完成。", "a001 与 a002 均能显示，type-check 和 build 通过。"],
    },
    tasks: [
      {
        title: "用判别联合描述请求四态",
        duration: 100,
        files: ["src/types/request.ts", "src/components/RequestStateDemo.vue", "src/views/HomeView.vue"],
        steps: [
          "定义 RequestState<T> 的 idle/loading/success/error 四个分支；success 只能有 data，error 只能有 message。",
          "写 RequestStateDemo，通过四个按钮切换状态，并使用 switch(state.status) 收窄。",
          "在 HomeView.vue 临时导入并渲染 RequestStateDemo，放在活动列表下方；Day 17 结束前再移除演示组件。",
          "故意在 error 分支读取 state.data，保存类型错误后修复。",
        ],
        expected: ["四个按钮分别显示待开始、加载中、数据、错误文案。", "error 分支无法读取 data。"],
        tests: ["npm run type-check", "浏览器首页依次点击四个状态按钮，页面不白屏且每次只显示一个状态"],
      },
      {
        title: "建立活动、用户与分页的数据合同",
        duration: 110,
        files: ["src/types/activity.ts", "src/types/user.ts", "src/types/pagination.ts", "src/types/request.ts"],
        steps: [
          "定义 User：id/name/role，role 仅为 student 或 organizer。",
          "定义 PaginationQuery：page/pageSize；PaginatedResult<T>：items/total/page/pageSize。",
          "把 Activity 改为 online/offline 判别联合：online 必须有 meetingUrl，offline 必须有 location。",
          "补完整 fixture：a003={id:'a003',title:'AI 学习分享',type:'tech',startAt:'2026-08-08T10:00:00+08:00',capacity:50,enrolledCount:10,mode:'online',meetingUrl:'https://example.com/meeting'}；a004={id:'a004',title:'校园志愿服务',type:'volunteer',startAt:'2026-08-09T09:00:00+08:00',capacity:20,enrolledCount:5,mode:'offline',location:'学生活动中心'}。",
          "分别故意漏掉 a003.meetingUrl 与 a004.location，确认类型报错后修复。",
        ],
        expected: ["线上卡片显示“线上”，线下卡片显示 location。", "不存在同时依赖 location 与 meetingUrl 的模糊分支。"],
        tests: ["npm run type-check", "online fixture 漏 meetingUrl 必须失败", "offline fixture 漏 location 必须失败"],
      },
      {
        title: "在页面中使用收窄并清理显式 any",
        duration: 110,
        files: ["src/views/HomeView.vue", "src/components/ActivityCard.vue", "src/mocks/activities.ts"],
        steps: [
          "在 ActivityCard 中根据 activity.mode 显示会议链接或地点。",
          "搜索 src 下的显式 any；逐处换成真实类型或 unknown + 收窄，不修改第三方声明。",
          "制造非法 role='admin' 和 page='2' 两个错误，确认能被类型检查捕获。",
        ],
        expected: ["a003 只显示会议入口，a004 只显示地点。", "src 业务代码无为逃避错误而添加的 any。"],
        tests: ["npm run type-check", "npm run build", "rg -n '\\bany\\b' src 并逐条解释保留项"],
      },
      {
        title: "算法与记录",
        duration: 40,
        files: ["algorithms/day16-reverse-list.ts", "algorithms/day16-reverse-list.test.ts", "notes/day-16.md"],
        steps: ["完成 LeetCode 206，先画 prev/current/next 三指针变化。", "在测试文件写空链表、单节点和 1→2→3 三个用例。", "记录空链表和单节点边界，提交 refactor: model domain states with types。"],
        expected: ["能徒手演示 1→2→3 反转过程。"],
        tests: ["npm run test:run -- algorithms/day16-reverse-list.test.ts", "空链表返回 null", "1→2→3 返回 3→2→1"],
      },
    ],
    optional: ["把 role 文案映射提取为 Record<UserRole, string>。"],
    review: {
      route: "/",
      steps: ["切换请求四态。", "查看线上/线下两张卡片。", "临时新增线上活动但不提供 meetingUrl，让学习者修复。"],
      expected: ["四态互斥且显示正确。", "学习者能解释判别字段如何帮助收窄。"],
    },
  },

  17: {
    start: {
      dir: "campus-growth-hub",
      commands: ["git status", "npm run type-check", "npm run test:run"],
      open: ["src/components/ActivityCard.vue", "src/components/SearchBar.vue", "src/views/HomeView.vue", "src/types/activity.ts", "src/mocks/activities.ts"],
      before: ["本日不引入网络 mock；请求层统一在 Day 20 使用 fetch + MSW 建立。", "Day 16 的 online/offline 与 RequestState 类型已通过检查。"],
    },
    tasks: [
      {
        title: "为组件 Props 与 Emits 建立明确边界",
        duration: 120,
        files: ["src/components/ActivityCard.vue", "src/components/SearchBar.vue", "src/views/HomeView.vue", "src/types/activity.ts"],
        steps: [
          "ActivityCard 使用 defineProps<{ activity: Activity; bookmarked: boolean }>()。",
          "沿用 Day 12 的事件名 toggle-bookmark：ActivityCard 使用 defineEmits<{ 'toggle-bookmark': [activityId: string] }>()，只携带 id，不改成第二个事件名。",
          "在 src/types/activity.ts 定义 ActivityQuery={keyword:string;type:ActivityType|'all';mode:ActivityMode|'all'}。沿用并改造 SearchBar.vue，不创建 ActivityFilters.vue；SearchBar 接收 modelValue:ActivityQuery 并发出 update:modelValue。",
          "同步更新真实父组件 HomeView.vue 的 SearchBar v-model 与 ActivityCard @toggle-bookmark；移除 Day 16 临时 RequestStateDemo。",
          "依次制造 emit 完整对象、keyword 传 number、bookmarked 漏传三个错误，保存错误信息后修复。",
        ],
        expected: ["点击收藏时父组件收到活动 id。", "筛选组件不直接修改 props。"],
        tests: ["npm run type-check", "点击 a001 收藏按钮，UI 状态切换且 Console 输出 a001"],
      },
      {
        title: "把本地 fixture 包装成类型明确的临时数据函数",
        duration: 80,
        files: ["src/services/activityFixture.ts", "src/services/activityFixture.test.ts", "src/types/api.ts", "src/types/pagination.ts"],
        steps: [
          "创建 listActivityFixtures(query): Promise<ApiResult<PaginatedResult<Activity>>>，只读取本地 fixture，并延迟 300ms。",
          "这里不封装 request、不模拟 HTTP、不安装 Axios；它只用于练习接口响应类型，Day 20 将被 fetch/MSW 替换。",
          "返回 items、total、page、pageSize；把返回字段 items 临时拼错为 item，确认类型检查失败。",
          "在 activityFixture.test.ts 使用 Vitest 测试 page=1/pageSize=2 返回两项，以及无匹配关键词返回空 items。",
        ],
        expected: ["函数 300ms 后返回分页结构。", "拼错响应字段会立即报错。"],
        tests: ["npm run type-check", "npm run test:run -- src/services/activityFixture.test.ts", "page=1,pageSize=2 时 items 长度为 2"],
      },
      {
        title: "把类型接入列表到卡片的数据流",
        duration: 120,
        files: ["src/views/HomeView.vue", "src/components/SearchBar.vue", "src/components/ActivityCard.vue", "src/services/activityFixture.ts"],
        steps: [
          "HomeView 中使用 ref<Activity[]>([]) 与 ref<RequestState<Activity[]>>，调用临时数据函数。",
          "筛选变化后重新加载；loading、success、empty、error 分支都由 RequestState 渲染。",
          "关闭资料后把 bookmark emit 从完整 Activity 改为 id 的链路重写一次。",
        ],
        expected: ["首次进入先显示加载中，再显示活动。", "筛选无结果显示空态，收藏仍正常。"],
        tests: ["npm run type-check", "npm run build", "输入不存在关键词时显示空态"],
      },
      {
        title: "算法与记录",
        duration: 40,
        files: ["algorithms/day17-cycle-list.ts", "algorithms/day17-cycle-list.test.ts", "notes/day-17.md"],
        steps: ["完成 LeetCode 141，画快慢指针相遇过程。", "在测试文件构造无环链表与单节点自环。", "记录无环、单节点自环，提交 refactor: type component boundaries。"],
        expected: ["能解释为什么快慢指针相遇表示有环。"],
        tests: ["npm run test:run -- algorithms/day17-cycle-list.test.ts", "[3,2,0,-4], pos=1 返回 true", "[1], pos=-1 返回 false"],
      },
    ],
    optional: ["为 SearchBar 增加 type='all'，不得使用类型断言绕过。"],
    review: {
      route: "/",
      steps: ["演示加载、空态和收藏。", "检查 toggle-bookmark emit 只携带 id；临时改成 Activity 后让学习者根据类型错误恢复父子组件约定。"],
      expected: ["type-check 通过。", "学习者能说明 props 保护输入、emit 约束输出。"],
    },
  },

  18: {
    start: {
      dir: "campus-growth-hub",
      commands: ["npm install vue-router", "git status", "npm run type-check", "npm run test:run"],
      open: ["src/main.ts", "src/App.vue", "src/components/ActivityCard.vue"],
      before: ["今天只建路由骨架、参数和 404，不做登录守卫。", "正式 authStore 与守卫统一在 Day 19 接入，避免先写临时认证再返工。"],
    },
    tasks: [
      {
        title: "创建页面与路由表",
        duration: 130,
        files: ["src/router/index.ts", "src/main.ts", "src/App.vue", "src/views/ActivityListView.vue", "src/views/ActivityDetailView.vue", "src/views/ProfileView.vue", "src/views/LoginView.vue", "src/views/NotFoundView.vue"],
        steps: [
          "配置 /activities、/activities/:id、/profile、/login 和 /:pathMatch(.*)*；根路径重定向到 /activities。",
          "在 main.ts 注册 router，在 App.vue 只保留主导航与 RouterView。",
          "把 src/views/HomeView.vue 重命名为 src/views/ActivityListView.vue，并更新 import；禁止复制代码后同时保留两套列表状态。",
          "ActivityDetailView 读取 route.params.id，并从 fixture 找活动。",
        ],
        expected: ["五个路径能直接输入访问。", "前进、后退和刷新均保持当前页面。"],
        tests: ["npm run type-check", "npm run build", "依次打开 /activities、/activities/a001、/profile、/login、/not-exist"],
      },
      {
        title: "接通卡片导航与业务无数据状态",
        duration: 100,
        files: ["src/components/ActivityCard.vue", "src/views/ActivityListView.vue", "src/views/ActivityDetailView.vue", "src/views/NotFoundView.vue"],
        steps: [
          "卡片标题使用 RouterLink 指向具名详情路由并传 id。",
          "详情 id=a001 显示活动；id=missing 显示“活动不存在”和返回列表按钮，但仍停留在详情路由。",
          "只有完全未知 URL 才进入全局 404，记录业务空态与路由 404 的区别。",
          "故意把详情参数名由 id 写成 activityId，复现 undefined 后通过 route 配置定位修复。",
        ],
        expected: ["点击卡片进入正确详情。", "missing 是业务空态，/abc 是全局 404。"],
        tests: ["打开 /activities/a001 显示 a001 标题", "打开 /activities/missing 显示活动不存在", "打开 /abc 显示 404"],
      },
      {
        title: "无 AI 重写一条动态路由并验证导航",
        duration: 90,
        files: ["src/router/index.ts", "notes/day-18.md"],
        steps: ["关闭文档，删除详情路由后凭记忆重写。", "记录 route 是当前路由信息、router 是导航器；分别写一个使用位置。", "用浏览器刷新、后退、前进完成回归。"],
        expected: ["重写后具名路由和动态参数仍工作。"],
        tests: ["npm run type-check", "npm run build", "浏览器历史前进后退无白屏"],
      },
      {
        title: "算法与提交",
        duration: 40,
        files: ["algorithms/day18-merge-lists.ts", "algorithms/day18-merge-lists.test.ts", "notes/day-18.md"],
        steps: ["完成 LeetCode 21，画 dummy/current 指针。", "用 Vitest 写两个空链表与两个非空有序链表用例。", "记录空链表边界，提交 feat: add typed application routes。"],
        expected: ["能解释 dummy 节点减少了哪个分支。"],
        tests: ["npm run test:run -- algorithms/day18-merge-lists.test.ts", "[] 与 [] 返回 []", "[1,2,4] 与 [1,3,4] 返回 [1,1,2,3,4,4]"],
      },
    ],
    optional: ["给当前导航项增加 aria-current 样式，不增加新页面。"],
    review: {
      route: "/activities",
      steps: ["从列表点击 a001。", "直接刷新详情。", "分别打开 /activities/missing 与 /unknown。"],
      expected: ["动态参数正确。", "业务空态与全局 404 可区分，所有路径无 Console 错误。"],
    },
  },

  19: {
    start: {
      dir: "campus-growth-hub",
      commands: ["npm install pinia", "git status", "npm run type-check", "npm run test:run"],
      open: ["src/main.ts", "src/router/index.ts", "src/views/LoginView.vue", "src/views/ActivityListView.vue"],
      before: ["Day 18 所有页面已存在，但 /profile 尚未受保护。", "今天才建立 authStore 并把守卫接入 router。"],
    },
    tasks: [
      {
        title: "注册 Pinia 并建立两个最小 store",
        duration: 120,
        files: ["src/main.ts", "src/stores/auth.ts", "src/stores/bookmarks.ts", "src/types/user.ts"],
        steps: [
          "在 main.ts 创建并注册 Pinia，顺序为 app.use(pinia).use(router).mount('#app')。",
          "authStore 定义 user、isAuthenticated、setDemoUser(user)、restoreSession、logout；演示用户固定为 s001/小林/student。Day 23 会新增唯一异步 action login(credentials)，不保留第二套登录链路。",
          "bookmarkStore 只保存 activityId[]，提供 toggle(id) 与 isBookmarked(id)，禁止保存完整 Activity。",
          "列表页改为从 bookmarkStore 读取和切换收藏。",
        ],
        expected: ["登录前 user 为 null；演示登录后显示小林。", "同一 id 不会重复进入 bookmarks。"],
        tests: ["npm run type-check", "连续 toggle a001 两次，最终未收藏", "toggle a001 一次后数组只含一个 a001"],
      },
      {
        title: "实现有边界的本地持久化",
        duration: 100,
        files: ["src/services/storage.ts", "src/services/storage.test.ts", "src/stores/auth.ts", "src/stores/bookmarks.ts"],
        steps: [
          "固定 key：cgh.session.v1 与 cgh.bookmarks.v1；只保存演示会话和 id 数组。",
          "restore 时用 try/catch 校验 JSON 和最小字段，非法内容删除并回到安全空状态。",
          "登录、登出、收藏变化后同步保存；登出清会话，不强制清收藏。",
          "在 DevTools 手动把 cgh.session.v1 改成 '{bad'，刷新验证不白屏。",
          "在 storage.test.ts 使用 Vitest 和 localStorage mock 测试正常读取、非法 JSON 返回 null 并清理 key。",
        ],
        expected: ["刷新后登录和收藏恢复。", "损坏存储时回到未登录且 Console 无未捕获异常。"],
        tests: ["npm run test:run -- src/services/storage.test.ts", "刷新后 a001 仍收藏", "localStorage 写入非法 JSON 后刷新进入未登录状态"],
      },
      {
        title: "接入路由守卫与退出闭环",
        duration: 100,
        files: ["src/router/index.ts", "src/views/LoginView.vue", "src/views/ProfileView.vue", "src/App.vue"],
        steps: [
          "给 /profile 增加 meta.requiresAuth=true；beforeEach 读取 authStore，未登录跳 /login?redirect=原路径。",
          "登录页按钮调用 loginDemoStudent，成功后回 redirect 或 /activities。",
          "主导航增加退出按钮；退出后若当前页需登录则跳 /login。",
          "说明 store 必须在 Pinia 安装后由守卫使用，禁止在 router 模块顶层错误创建未激活 store。",
        ],
        expected: ["未登录直达 /profile 被拦截。", "登录后回到 /profile；刷新保持；退出回登录页。"],
        tests: ["npm run type-check", "npm run build", "清空 storage 后打开 /profile → 登录 → 返回 /profile → 刷新 → 退出"],
      },
      {
        title: "算法与记录",
        duration: 40,
        files: ["algorithms/day19-tree-depth.ts", "algorithms/day19-tree-depth.test.ts", "notes/day-19.md"],
        steps: ["完成 LeetCode 104，先写递归终止条件。", "用 Vitest 写空树与三层树用例。", "记录空树边界和持久化风险，提交 feat: add auth and bookmark stores。"],
        expected: ["能解释为什么深度是左右子树最大值加一。"],
        tests: ["npm run test:run -- algorithms/day19-tree-depth.test.ts", "空树返回 0", "[3,9,20,null,null,15,7] 返回 3"],
      },
    ],
    optional: ["为 storage 数据增加 version 字段；不安装 Pinia 持久化插件。"],
    review: {
      route: "/profile",
      steps: ["清空 storage 后直达 /profile。", "演示登录、收藏、刷新、退出。", "写入损坏 session 再刷新。"],
      expected: ["守卫顺序正确。", "状态恢复且损坏数据不会白屏；学习者能解释为何筛选条件不进 Pinia。"],
    },
  },

  20: {
    start: {
      dir: "campus-growth-hub",
      commands: ["npm install -D msw", "npx msw init public --save", "git status", "npm run type-check", "npm run test:run"],
      open: ["src/main.ts", "src/services/activityFixture.ts", "src/views/ActivityListView.vue", "src/views/ActivityDetailView.vue"],
      before: ["本计划唯一请求方案为原生 fetch + MSW；不安装 Axios、json-server 或第二套 mock。", "保留 fixture 数据，但 Day 17 的临时 activityFixture 服务将在今天删除。"],
    },
    tasks: [
      {
        title: "建立唯一的 MSW HTTP mock",
        duration: 110,
        files: ["src/mocks/browser.ts", "src/mocks/handlers.ts", "src/mocks/activities.ts", "src/mocks/raceActivities.ts", "src/main.ts", "public/mockServiceWorker.js", ".env", ".env.example"],
        steps: [
          "browser.ts 使用 setupWorker；handlers.ts 提供 GET /api/activities 与 GET /api/activities/:id。",
          "列表 handler 支持 q/page/pageSize/mode；默认延迟 300ms。",
          "固定 .env 与 .env.example 均写 VITE_API_BASE_URL=/api；后续 request 只从 import.meta.env.VITE_API_BASE_URL 读取前缀。",
          "在 raceActivities.ts 固定 raceSlow={id:'race-slow',title:'旧请求结果 slow',...完整 Activity 字段} 与 raceFast={id:'race-fast',title:'最新请求结果 fast',...完整字段}；q=slow/fast 时 handler 直接返回对应单项，不再按普通标题筛选。",
          "main.ts 固定启动形状：async function enableMocking(){ if(!import.meta.env.DEV) return; const { worker }=await import('./mocks/browser'); return worker.start({onUnhandledRequest:'bypass'}); }；先 await enableMocking()，再 createApp(App).use(pinia).use(router).mount('#app')。",
          "删除 Day 17 临时 activityFixture 服务的调用，所有活动读取改走 HTTP。",
        ],
        expected: ["Network 中能看到 /api/activities 请求。", "Service Worker 激活，页面仍显示 fixture。"],
        tests: ["npm run type-check", "npm run dev 后 Network 出现 /api/activities?page=1&pageSize=6", "npm run build"],
      },
      {
        title: "封装 fetch、超时和错误分类",
        duration: 100,
        files: ["src/api/request.ts", "src/api/request.test.ts", "src/api/activity.ts", "src/types/api.ts", "src/mocks/handlers.ts"],
        steps: [
          "定义 ApiErrorResponse={code:number;message:string}，错误响应不再假装满足必须含 data 的 ApiResult<T>。",
          "request<T>(path,{signal,timeoutMs=5000}) 内创建自己的 controller；外部 signal 已 aborted 时立即 abort，否则注册一次性 abort 监听；setTimeout 到期前先记录 timedOut=true 再 abort。finally 必须 clearTimeout 并移除监听。",
          "fetch 使用 `${import.meta.env.VITE_API_BASE_URL}${path}`。response.ok=false 时先解析 ApiErrorResponse，再抛 kind='business'；AbortError 根据 timedOut 区分 timeout/aborted；其余 TypeError 归 network。aborted 由页面忽略，不进入 error UI。",
          "MSW 固定故障：mode=business-error 返回 400 {code:40001,message:'活动查询失败'}；mode=timeout 延迟 3000ms；浏览器 Offline 制造 network。",
          "request.test.ts 使用 msw/node 的 setupServer 建正常、400、3000ms 三个 handler，分别断言 success/business/timeout，并用外部 AbortController 断言 aborted。",
          "activity API 只负责路径和查询参数，页面不得直接 fetch。",
        ],
        expected: ["三种错误显示不同文案。", "取消请求不闪现错误状态。"],
        tests: ["npm run test:run -- src/api/request.test.ts", "mode=business-error 显示活动查询失败", "timeoutMs=500 + mode=timeout 显示请求超时", "Offline 时显示网络不可用"],
      },
      {
        title: "接通列表、详情与连续搜索取消",
        duration: 110,
        files: ["src/composables/useActivitySearch.ts", "src/views/ActivityListView.vue", "src/views/ActivityDetailView.vue", "src/api/activity.ts", "src/mocks/handlers.ts"],
        steps: [
          "useActivitySearch 固定声明 let activeController: AbortController | null=null；每次搜索先 activeController?.abort()，再把新 controller 赋给它；组件卸载时也调用 activeController?.abort()。",
          "为 q=slow 固定延迟 1200ms，为 q=fast 固定延迟 200ms；先输入 slow 再立即输入 fast。",
          "列表和详情统一显示 loading/empty/error，并提供重试按钮。",
          "画出 View → composable → activity API → request → MSW → View 数据流。",
        ],
        expected: ["slow 后输入 fast，最终只显示 fast 结果。", "详情请求也经过统一 request。"],
        tests: ["npm run type-check", "npm run build", "slow→fast 竞态测试三次均只显示 fast", "错误态点击重试可恢复"],
      },
      {
        title: "旧题复现与阶段记录",
        duration: 40,
        files: ["algorithms/day20-review.ts", "algorithms/day20-review.test.ts", "notes/day-20.md"],
        steps: ["从空白重做本周最薄弱的一道链表或树题，并把该题的两个旧用例写入 day20-review.test.ts。", "记录 MSW、request 和页面职责，提交 refactor: integrate typed application data flow。"],
        expected: ["能不看代码画出完整请求数据流。"],
        tests: ["npm run test:run -- algorithms/day20-review.test.ts", "算法包含复杂度和一个边界", "git diff 无 Day 17 临时 service 的残留调用"],
      },
    ],
    optional: ["在 MSW handler 中增加 401 fixture，但不做自动刷新 token。"],
    review: {
      route: "/activities",
      steps: ["在 Network 查看正常请求。", "依次触发 business-error、timeout、Offline。", "快速输入 slow 后 fast。"],
      expected: ["错误分类正确且可重试。", "最终只显示 fast；学习者能指出取消发生在哪一层。"],
    },
  },

  21: {
    start: {
      dir: "campus-growth-hub",
      commands: ["git status", "npm run type-check", "npm run test:run"],
      open: ["src/router/index.ts", "src/stores/auth.ts", "src/stores/bookmarks.ts", "src/api/request.ts"],
      before: ["轻量日只做复现和自测，不引入新库。", "学习者先保存当前 commit，再按任务步骤逐个注入两个固定故障；每次修复后恢复干净状态，再进行下一题。学习过程独立完成。"],
    },
    tasks: [
      {
        title: "解释四个核心文件并画数据流",
        duration: 35,
        files: ["src/router/index.ts", "src/stores/auth.ts", "src/stores/bookmarks.ts", "src/api/request.ts", "notes/day-21.md"],
        steps: ["每个文件用一句话说明输入、输出和职责。", "画出页面→store/API→request→MSW→页面，标出错误返回路径。"],
        expected: ["四个文件职责不混淆。"],
        tests: ["随机指一行能说明它属于哪一层"],
      },
      {
        title: "修复两个确定的预设故障",
        duration: 55,
        files: ["src/mocks/activities.ts", "src/types/activity.ts", "src/router/index.ts", "notes/day-21.md"],
        steps: [
          "学习者先把干净 commit hash 写入 notes/day-21.md。然后只看本步骤自行注入故障一：在 src/mocks/activities.ts 的 id:'a001' 对象中，把 capacity:30 改为 capacity:'30'；从 type-check 输出定位并恢复 number。",
          "确认故障一已修复且工作区干净后，学习者自行注入故障二：把详情路由 path 中的 :id 改为 :activityId，但详情仍读取 id；从 /activities/a001 的“活动不存在”定位并统一参数名。",
          "每个故障记录复现、预期、实际、根因和验证命令；修复后用 git diff 对照干净 commit，确认只撤销两处注入。",
        ],
        expected: ["type-check 恢复通过。", "a001 详情恢复。"],
        tests: ["npm run type-check", "打开 /activities/a001", "npm run build"],
      },
      {
        title: "完成当前阶段最小回归",
        duration: 60,
        files: ["notes/day-21.md"],
        steps: ["按顺序演示临时学生登录、刷新、列表请求、详情、收藏、错误重试和退出。", "从空白重写 bookmarkStore 的 isBookmarked(id) 或重做一道链表/树旧题，二选一。", "提交 fix: pass engineering phase review。"],
        expected: ["所有路径无未捕获错误。", "至少一个 D/E 项降到 B/C。"],
        tests: ["Console 无红色错误", "Network 无重复失控请求", "回归步骤全部勾选"],
      },
    ],
    optional: ["无；轻量日完成后停止学习。"],
    review: {
      route: "/activities",
      steps: ["检查两个故障记录。", "随机抽一个核心文件说明数据流。", "现场取消收藏并确认列表和详情同步。"],
      expected: ["150 分钟学习任务结束，不补新课。", "两个故障均能复现、解释和验证。"],
    },
  },

  22: {
    start: {
      dir: "campus-growth-hub",
      commands: ["git status", "npm run type-check", "npm run test:run", "npm run build"],
      open: ["README.md", "src/router/index.ts", "src/views/ActivityListView.vue", "src/views/ActivityDetailView.vue", "src/views/ProfileView.vue", "src/views/LoginView.vue", "src/views/NotFoundView.vue", "src/stores/auth.ts", "src/stores/bookmarks.ts", "src/api/request.ts", "src/api/activity.ts"],
      before: ["本日不是重新立项；Day 10–21 已完成的是原型。", "今日名称与目标固定为“现有原型审计与后续范围冻结”，禁止重建项目。"],
    },
    tasks: [
      {
        title: "盘点现有原型而非从头设计",
        duration: 90,
        files: ["docs/current-inventory.md", "src/router/index.ts", "src/views", "src/stores", "src/api"],
        steps: [
          "按页面、组件、store、API、mock 五类列出现有文件和已经能演示的功能。",
          "每项标记 works/partial/missing，并写一条可观察证据。",
          "把 Day 21 未通过项映射到具体文件，不写“继续完善”之类模糊任务。",
        ],
        expected: ["清单能对应真实文件。", "没有创建第二套列表、store 或 request。"],
        tests: ["随机抽 5 条 inventory 均能打开对应文件或页面", "npm run type-check"],
      },
      {
        title: "冻结 12 天可完成的范围",
        duration: 100,
        files: ["docs/scope.md", "docs/user-stories.md", "docs/data-model.md"],
        steps: [
          "范围上限：student/organizer 两角色；活动列表、详情、个人中心、登录、组织者管理、数据看板六类页面。",
          "Must 闭环：学生登录→筛选→详情→收藏/报名→个人中心；组织者登录→新增/编辑活动→查看报名统计。",
          "明确 Won't：完整后端、真实支付、聊天、复杂审批、文件上传、token 刷新。",
          "每个用户故事使用 Given/When/Then，并给失败或空状态一条验收。",
          "数据模型明确 User、Activity、Enrollment、ActivityQuery 的主键与关系。",
        ],
        expected: ["Must 不超过 8 条用户故事。", "每条故事可在半天内验收。"],
        tests: ["每个 Must 有 Given/When/Then", "每个页面都能映射至少一条故事", "Won't 列表不少于 5 项"],
      },
      {
        title: "建立可执行看板与仓库说明",
        duration: 130,
        files: ["README.md", "docs/task-board.md", ".env.example", "docs/architecture.md"],
        steps: [
          "README 写项目问题、角色、当前功能、技术栈、启动命令、演示账号占位规则和 mock 说明。",
          "task-board 使用 Todo/Doing/Done/Backlog，每项含文件范围、预计分钟数、完成标准；Doing 同时最多 1 项。",
          "核对 Day 20 已创建的 .env.example 只列 VITE_API_BASE_URL=/api，不写密钥；同时确认 request.ts 确实读取该变量，不再创建未使用的环境变量。",
          "architecture 用 Mermaid 画 View→Store/API→request→MSW 数据流。",
          "运行项目回归，确认文档整理未改变功能。",
        ],
        expected: ["新同学按 README 能启动。", "下一日第一项任务可直接从看板取出。"],
        tests: ["npm run type-check", "npm run build", "按 README 从零核对安装和启动命令"],
      },
      {
        title: "算法与提交",
        duration: 40,
        files: ["algorithms/day22-inorder.ts", "algorithms/day22-inorder.test.ts", "notes/day-22.md"],
        steps: ["完成 LeetCode 94，递归或迭代只选一种。", "用 Vitest 写空树与题目示例。", "提交 docs: audit prototype and freeze scope。"],
        expected: ["能说明中序遍历次序。"],
        tests: ["npm run test:run -- algorithms/day22-inorder.test.ts", "空树返回 []", "[1,null,2,3] 返回 [1,3,2]"],
      },
    ],
    optional: ["为 README 添加一张当前页面截图；不做视觉重设计。"],
    review: {
      route: "/activities",
      steps: ["先演示现有原型。", "从 inventory 指向对应文件。", "从 scope 临时删除数据看板并说明为何不破坏学生主闭环。"],
      expected: ["能明确说出已完成、未完成和不做。", "范围足以在 Day 23–34 内完成。"],
    },
  },

  23: {
    start: {
      dir: "campus-growth-hub",
      commands: ["git status", "npm run type-check", "npm run test:run"],
      open: ["src/stores/auth.ts", "src/router/index.ts", "src/views/LoginView.vue", "src/mocks/handlers.ts"],
      before: ["Pinia 和基础 requiresAuth 守卫来自 Day 19。", "今日演示账号固定，不接真实后端、不存真实密码。"],
    },
    tasks: [
      {
        title: "建立可重复的演示认证 fixture",
        duration: 90,
        files: ["src/mocks/users.ts", "src/mocks/handlers.ts", "src/api/auth.ts", "src/types/user.ts"],
        steps: [
          "固定学生 student@example.com/student123，组织者 organizer@example.com/organizer123。",
          "POST /api/login：正确凭据返回 user 与 demo-session；错误凭据返回 401 和“账号或密码错误”；延迟 500ms。",
          "auth API 通过统一 request 调用；不得在 LoginView 直接读取 users fixture。",
        ],
        expected: ["Network 可见 POST /api/login。", "正确和错误账号结果稳定可复现。"],
        tests: ["npm run type-check", "错误密码返回业务错误", "两类正确账号返回不同 role"],
      },
      {
        title: "完成登录表单、会话恢复与退出",
        duration: 110,
        files: ["src/views/LoginView.vue", "src/stores/auth.ts", "src/services/storage.ts", "src/App.vue"],
        steps: [
          "表单含邮箱和密码；空值、邮箱格式、密码少于 6 位在前端提示。",
          "唯一登录链路固定为 LoginView → authStore.login(credentials) → authApi.login → request → MSW → authStore.persist；删除 Day 19 的 setDemoUser 对外按钮调用，LoginView 不直接调用 authApi。",
          "authStore.login 内维护 isSubmitting 与同一个 pending promise，已有请求时直接返回该 promise；按钮同时绑定 disabled，连续点击只发一个请求；401 由 store 保留为可展示 message，显示在表单内。",
          "成功后按 redirect 返回；刷新恢复会话；退出清会话并回 /login。",
          "演示密码只写 README，不保存到 localStorage。",
        ],
        expected: ["错误不会清空用户已输入邮箱。", "刷新受保护页仍保持登录。"],
        tests: ["空表单不发请求", "连续双击仅一个 login 请求", "登录→刷新→退出完整通过"],
      },
      {
        title: "增加角色路由、导航和 403",
        duration: 120,
        files: ["src/router/index.ts", "src/views/ForbiddenView.vue", "src/views/OrganizerActivitiesView.vue", "src/App.vue", "src/router/route-meta.d.ts"],
        steps: [
          "给 /organizer/activities 设置 requiresAuth=true、roles=['organizer']。",
          "守卫顺序：未登录→/login；已登录但角色不符→/403；允许则继续。",
          "导航只向 organizer 显示管理入口；student 不显示，但隐藏导航不能替代守卫。",
          "分别测试学生直输管理 URL、组织者访问、刷新管理页、损坏会话。",
        ],
        expected: ["学生进入 /403。", "组织者进入管理占位页；刷新不丢权限。"],
        tests: ["npm run type-check", "npm run build", "student→/organizer/activities 得 403", "organizer→/organizer/activities 成功"],
      },
      {
        title: "算法与记录",
        duration: 40,
        files: ["algorithms/day23-climb.ts", "algorithms/day23-climb.test.ts", "notes/day-23.md"],
        steps: ["完成 LeetCode 70，写 dp[i] 的含义再编码。", "用 Vitest 写 n=1、2、5 三个用例。", "记录前端守卫不能替代服务端鉴权，提交 feat: complete role-based auth flow。"],
        expected: ["能解释初始状态与转移方程。"],
        tests: ["npm run test:run -- algorithms/day23-climb.test.ts", "n=1 返回1", "n=2 返回2", "n=5 返回8"],
      },
    ],
    optional: ["根据 redirect 在登录页显示“登录后将返回个人中心”，不做注册。"],
    review: {
      route: "/login",
      steps: ["验证空表单、错误密码、学生登录、组织者登录、刷新与退出。", "学生直达 /organizer/activities。"],
      expected: ["请求不会重复提交。", "角色路由和导航一致，学生得到 403。"],
    },
  },

  24: {
    start: {
      dir: "campus-growth-hub",
      commands: ["git status", "npm run type-check", "npm run test:run"],
      open: ["src/views/ActivityListView.vue", "src/components/SearchBar.vue", "src/api/activity.ts", "src/mocks/handlers.ts", "src/mocks/activities.ts"],
      before: ["沿用 Day 11/17 的筛选组件和 Day 20 的 fetch + MSW，不新建第二套。", "fixture 至少补到 15 条；pageSize 固定 6，确保能看到 3 页。"],
    },
    tasks: [
      {
        title: "固定查询合同与足量 fixture",
        duration: 80,
        files: ["src/types/activity.ts", "src/types/pagination.ts", "src/mocks/activities.ts", "src/mocks/activityFilter.ts", "src/mocks/activityFilter.test.ts", "src/mocks/handlers.ts"],
        steps: [
          "ActivityQuery 固定 keyword/type/mode/availableOnly/page/pageSize。",
          "保留 a001-a004，并按固定矩阵补 a005-a015：a005 前端工程化/tech/online/40/8，a006 篮球训练/sports/offline/20/20，a007 社区支教/volunteer/offline/30/12，a008 TypeScript 分享/tech/online/50/18，a009 羽毛球赛/sports/offline/16/10，a010 环保宣传/volunteer/offline/25/25，a011 Vue 工作坊/tech/offline/24/6，a012 跑步打卡/sports/online/100/31，a013 图书整理/volunteer/offline/15/4，a014 AI 项目夜谈/tech/online/60/22，a015 校运会志愿者/volunteer/offline/80/35。每条补唯一 startAt；online 补唯一 meetingUrl，offline 补 location。",
          "确认 a003 标题仍为 AI 学习分享，因此答案卡 /activities?q=AI&type=tech 必有结果；a006、a010 为已满。",
          "handler 先筛选再分页，返回 items/total/page/pageSize。",
          "非法 page<1 归一为 1；page 超出总页数时返回最后有效页。",
          "把筛选与分页提取为纯函数 filterAndPaginateActivities，并在 activityFilter.test.ts 测默认 3 页、AI+tech、availableOnly 和非法页码。",
        ],
        expected: ["默认共 3 页。", "筛选和分页结果可预测。"],
        tests: ["npm run test:run -- src/mocks/activityFilter.test.ts", "GET /api/activities?page=1&pageSize=6 返回6条", "availableOnly=true 不返回已满活动", "所有 fixture id 唯一"],
      },
      {
        title: "实现 URL 驱动的筛选与分页",
        duration: 130,
        files: ["src/composables/useActivityQuery.ts", "src/utils/activityQuery.ts", "src/utils/activityQuery.test.ts", "src/components/SearchBar.vue", "src/views/ActivityListView.vue", "src/router/index.ts"],
        steps: [
          "把 route.query 到 ActivityQuery 的解析提取为纯函数 parseActivityQuery(raw)，useActivityQuery 只负责调用它和 router.replace；在 activityQuery.test.ts 测正常 query、page=abc、未知 type。",
          "从 route.query 初始化筛选；变化后用 router.replace 写回 q/type/mode/available/page。",
          "映射表固定为 route.q↔ActivityQuery.keyword、route.available↔ActivityQuery.availableOnly，其余同名；禁止同时生成 keyword 与 q 两套 URL。",
          "关键词、类型或模式变化时 page 重置为 1；翻页只改变 page。",
          "刷新 /activities?q=AI&type=tech&page=2 后条件和页码保持。",
          "处理 page=abc、page=-2 和未知 type，归一后页面不白屏。",
        ],
        expected: ["URL 可复制并恢复相同列表。", "筛选变化不会停留在空的旧页码。"],
        tests: ["npm run test:run -- src/utils/activityQuery.test.ts", "刷新带 query 的 URL", "浏览器前进后退恢复筛选", "page=abc 归一为1"],
      },
      {
        title: "补全 loading、empty、error 与竞态",
        duration: 110,
        files: ["src/views/ActivityListView.vue", "src/composables/useActivitySearch.ts", "src/mocks/handlers.ts"],
        steps: [
          "请求期间显示 skeleton 或明确加载文案；无结果显示清空筛选按钮；错误显示重试。",
          "MSW 保留 q=slow/fast 与 mode=business-error；取消旧请求的逻辑继续有效。开发环境下把页面 query debug=business-error/timeout 映射为 API 的 mode 参数，生产环境忽略 debug；验收用 /activities?debug=business-error 稳定触发。",
          "每个页面状态只出现一个主区域，旧数据是否保留必须写入说明。",
        ],
        expected: ["四态可稳定触发。", "slow→fast 不被旧结果覆盖。"],
        tests: ["q=不存在 显示空态", "mode=business-error 显示重试", "slow→fast 连续3次正确", "npm run build"],
      },
      {
        title: "算法与提交",
        duration: 40,
        files: ["algorithms/day24-stock.ts", "algorithms/day24-stock.test.ts", "notes/day-24.md"],
        steps: ["完成 LeetCode 121，先写 minPrice 与 maxProfit 的含义。", "用 Vitest 写波动数组与递减数组。", "提交 feat: build searchable activity catalog。"],
        expected: ["能解释为何只需一次遍历。"],
        tests: ["npm run test:run -- algorithms/day24-stock.test.ts", "[7,1,5,3,6,4] 返回5", "递减数组返回0"],
      },
    ],
    optional: ["增加日期筛选；只有 Must 全部通过后才做。"],
    review: {
      route: "/activities?q=AI&type=tech&page=1",
      steps: ["刷新并确认 AI+tech 至少出现 a003。", "新增“仅看可报名”，再次刷新。", "用 /activities?debug=business-error 触发错误态，再执行 slow→fast。"],
      expected: ["URL、UI、请求参数三者一致。", "错误与竞态均可解释。"],
    },
  },

  25: {
    start: {
      dir: "campus-growth-hub",
      commands: ["git status", "npm run type-check", "npm run test:run"],
      open: ["src/views/ActivityDetailView.vue", "src/stores/bookmarks.ts", "src/mocks/handlers.ts", "src/types/activity.ts"],
      before: ["收藏 store 来自 Day 19，今天只接入详情，不重写。", "更新策略固定为保守更新；乐观更新只做口述，不实现第二套。"],
    },
    tasks: [
      {
        title: "完成详情的正常、已满与不存在状态",
        duration: 90,
        files: ["src/views/ActivityDetailView.vue", "src/api/activity.ts", "src/mocks/handlers.ts", "src/mocks/activities.ts"],
        steps: [
          "固定 a001 可报名、a002 已满、missing 不存在。",
          "详情显示时间、模式、地点/链接、容量、已报名数；加载与错误独立呈现。",
          "a002 报名按钮禁用并显示已满；missing 显示业务空态。",
        ],
        expected: ["三个 id 产生三个确定页面结果。"],
        tests: ["/activities/a001 可报名", "/activities/a002 按钮禁用", "/activities/missing 显示活动不存在"],
      },
      {
        title: "接通详情收藏与报名 API",
        duration: 130,
        files: ["src/components/enrollment/EnrollmentForm.vue", "src/api/enrollment.ts", "src/stores/enrollments.ts", "src/mocks/enrollmentDb.ts", "src/mocks/enrollmentDb.test.ts", "src/mocks/handlers.ts", "src/views/ActivityDetailView.vue"],
        steps: [
          "报名表单只含手机号和备注；手机号使用中国大陆 11 位规则，备注最多 100 字。",
          "建立唯一 mock 报名数据源 enrollmentDb：localStorage key 固定 cgh.mock-enrollments.v1，值为 Enrollment[]；清除该 key 时恢复空数组。所有 MSW enrollment handler 都只通过 enrollmentDb 读写。",
          "增加 GET /api/enrollments?userId=s001 用于刷新恢复；POST /api/enrollments 接收 userId/activityId/phone/note，重复 userId+activityId 返回 409，a002 返回 400 已满。",
          "enrollmentStore 提供 load(userId) 与 enroll(payload)：登录恢复或刷新后先 GET；成功 POST 后再更新 store。",
          "提交中禁用按钮；成功后数据库与 store 保存 Enrollment{id,activityId,userId,status:'confirmed'}，页面显示已报名。",
          "固定手机号 18800000000 触发 500 {code:50001,message:'报名服务暂不可用'}；失败时 enrollmentDb 与 store 均不写入，按钮恢复。",
          "在 enrollmentDb.test.ts 使用 localStorage mock 测试初始空数组、写入后重载仍存在、重复 userId+activityId 被识别。",
          "收藏按钮复用 bookmarkStore；详情页收藏状态固定写成 computed(() => bookmarkStore.isBookmarked(activityId))，禁止复制为本地 ref，刷新后状态保留。",
        ],
        expected: ["成功只产生一条报名。", "失败不会伪造成功状态。"],
        tests: ["npm run test:run -- src/mocks/enrollmentDb.test.ts", "空手机号不发请求", "连续双击只有一个POST", "重复报名显示已报名", "手机号18800000000失败后可再次提交"],
      },
      {
        title: "回归学生核心闭环",
        duration: 100,
        files: ["src/views/ActivityListView.vue", "src/views/ActivityDetailView.vue", "src/stores/bookmarks.ts", "src/stores/enrollments.ts", "notes/day-25.md"],
        steps: ["从列表进入 a001，收藏并报名，再刷新详情。", "从列表进入 a002，确认已满不可提交。", "记录保守更新的数据流及重复提交防护位置。"],
        expected: ["发现→详情→收藏/报名闭环可重复演示。"],
        tests: ["npm run type-check", "npm run build", "Console 无错误", "刷新后收藏与报名状态仍在"],
      },
      {
        title: "算法与提交",
        duration: 40,
        files: ["algorithms/day25-max-subarray.ts", "algorithms/day25-max-subarray.test.ts", "notes/day-25.md"],
        steps: ["完成 LeetCode 53，写 current 与 best 的含义。", "用 Vitest 写题目示例与全负数。", "提交 feat: complete student enrollment flow。"],
        expected: ["能解释为何负贡献可舍弃。"],
        tests: ["npm run test:run -- algorithms/day25-max-subarray.test.ts", "[-2,1,-3,4,-1,2,1,-5,4] 返回6", "[-1] 返回-1"],
      },
    ],
    optional: ["为手机号输入增加格式化显示；不增加更多报名字段。"],
    review: {
      route: "/activities/a001",
      steps: ["演示收藏、手机号校验、双击提交、成功刷新后由 GET /api/enrollments 恢复。", "打开 a002 和 missing。", "用手机号18800000000触发报名失败。"],
      expected: ["状态和按钮行为一致。", "学习者能指出活动已满、重复提交和失败恢复分别在哪一层处理。"],
    },
  },

  26: {
    start: {
      dir: "campus-growth-hub",
      commands: ["git status", "npm run type-check", "npm run test:run"],
      open: ["src/stores/bookmarks.ts", "src/stores/enrollments.ts", "src/views/ProfileView.vue", "src/api/activity.ts"],
      before: ["数据源规则：活动来自 activity API；bookmarkStore 只存 id；enrollmentStore 只存报名记录。", "禁止把完整 Activity 复制进两个 store。"],
    },
    tasks: [
      {
        title: "建立个人中心的派生数据",
        duration: 110,
        files: ["src/views/ProfileView.vue", "src/stores/bookmarks.ts", "src/stores/enrollments.ts", "src/composables/usePersonalActivities.ts"],
        steps: [
          "usePersonalActivities 获取活动源数据，再把 bookmark ids 和 enrollment records 映射成两个列表。",
          "给 GET /api/activities 增加 ids=a001,a008 查询：ids 存在时按 id 集合返回全部命中活动且不受默认 pageSize=6 限制；usePersonalActivities 合并收藏 id 与报名 activityId 后用一次 ids 请求获取源数据。",
          "个人中心使用“我的收藏/我的报名”两个区块或 tabs，明确空状态。",
          "当收藏 id=deleted 不存在于活动源时忽略并显示一条可清理提示，不让页面报错。",
        ],
        expected: ["收藏和报名均来自派生，而非复制对象。", "空列表和脏 id 均不白屏。"],
        tests: ["无收藏时显示空态", "手动加入 deleted id 后页面仍可用", "npm run type-check"],
      },
      {
        title: "实现取消报名与失败恢复",
        duration: 100,
        files: ["src/api/enrollment.ts", "src/mocks/handlers.ts", "src/stores/enrollments.ts", "src/views/ProfileView.vue"],
        steps: [
          "DELETE /api/enrollments/:id 成功后从 cgh.mock-enrollments.v1 删除并返回 204，store 随后移除；mode=cancel-error 返回 500 且 enrollmentDb 不变。",
          "开发环境下把 /profile?debug=cancel-error 映射为 DELETE 的 mode=cancel-error，生产环境忽略 debug；验收固定使用该 URL。",
          "取消中禁用该条按钮；失败保留报名记录并显示重试。",
          "取消成功后回详情应显示可报名；刷新后保持取消状态。",
        ],
        expected: ["失败不会先消失后又跳回。", "成功时个人中心和详情一致。"],
        tests: ["npm run test:run -- src/mocks/enrollmentDb.test.ts", "/profile?debug=cancel-error 后记录仍在", "成功取消后详情可报名", "刷新后 GET /api/enrollments 仍未报名"],
      },
      {
        title: "验证列表、详情、个人中心跨页一致",
        duration: 110,
        files: ["src/views/ActivityListView.vue", "src/views/ActivityDetailView.vue", "src/views/ProfileView.vue", "notes/day-26.md"],
        steps: [
          "列表收藏 a001→详情显示已收藏→个人中心出现。",
          "个人中心取消收藏→返回详情显示未收藏→列表也未收藏。",
          "报名与取消执行同样路径；使用浏览器后退和刷新再次确认。",
          "画出活动源、收藏 id、报名记录和 computed 派生关系。",
        ],
        expected: ["三个页面从同一状态源得到一致结果。"],
        tests: ["npm run type-check", "npm run build", "两条跨页路径各执行两次", "Console 无错误"],
      },
      {
        title: "算法与提交",
        duration: 40,
        files: ["algorithms/day26-longest-substring.ts", "algorithms/day26-longest-substring.test.ts", "notes/day-26.md"],
        steps: ["LeetCode 3 允许看一次提示，画窗口左右边界。", "用 Vitest 写 abcabcbb、bbbbb、空字符串。", "提交 feat: add personal activity center。"],
        expected: ["至少能讲清暴力法；完成滑动窗口则说明 map 保存什么。"],
        tests: ["npm run test:run -- algorithms/day26-longest-substring.test.ts", "abcabcbb 返回3", "bbbbb 返回1", "空字符串返回0"],
      },
    ],
    optional: ["给个人中心增加状态标签 confirmed/cancelled；不引入缓存库。"],
    review: {
      route: "/profile",
      steps: ["从个人中心取消 a001 收藏和报名。", "返回详情及列表检查，再刷新验证 GET 恢复。", "用 /profile?debug=cancel-error 触发取消失败。"],
      expected: ["三个页面一致。", "学习者能指出唯一源数据和派生数据，失败时状态不丢。"],
    },
  },

  27: {
    start: {
      dir: "campus-growth-hub",
      commands: ["git status", "npm run type-check", "npm run test:run"],
      open: ["src/utils/activityQuery.ts", "src/composables/useActivitySearch.ts", "src/stores/bookmarks.ts", "src/views/ActivityDetailView.vue", "docs/task-board.md"],
      before: ["学习者保存当前 commit；按任务步骤逐个注入两个固定故障，每次只处理一题并记录证据。学习过程独立完成。", "今天不新增功能，先修回归。"],
    },
    tasks: [
      {
        title: "无 AI 重写筛选 composable 的核心",
        duration: 110,
        files: ["src/utils/activityQuery.rebuild.ts", "src/utils/activityQuery.rebuild.test.ts", "src/utils/activityQuery.ts", "notes/day-27.md"],
        steps: [
          "在 rebuild 文件从空白实现纯函数 parseActivityQuery(raw)：解析 q/type/mode/available/page，不依赖 route 或 router；筛选更新与 router.replace 不在本次重写范围。",
          "40 分钟后才对照原实现 10 分钟，再关掉原文件修正 rebuild。",
          "在 rebuild.test.ts 用 Vitest 写 3 个输入：正常 query、page=abc、未知 type。",
        ],
        expected: ["不复制旧文件也能写出核心解析和更新。"],
        tests: ["npm run type-check", "npm run test:run -- src/utils/activityQuery.rebuild.test.ts", "三个 query 用例输出确定", "能解释每个类型收窄"],
      },
      {
        title: "定位竞态预设故障",
        duration: 80,
        files: ["src/composables/useActivitySearch.ts", "src/mocks/handlers.ts", "notes/day-27.md"],
        steps: [
          "学习者自行注入故障一：在 src/composables/useActivitySearch.ts 注释掉发起请求前的 activeController?.abort() 这一行，其余代码不动。",
          "学习者输入 slow 后立即输入 fast，记录最终错误显示 slow。",
          "只改一个假设，恢复该 activeController?.abort()；连续运行 3 次验证。",
        ],
        expected: ["修复后三次最终结果均为 fast。"],
        tests: ["slow→fast 连续3次", "取消请求不显示错误", "Network 可解释"],
      },
      {
        title: "定位跨页状态副本故障并完成回归",
        duration: 130,
        files: ["src/views/ActivityDetailView.vue", "src/stores/bookmarks.ts", "docs/student-regression.md", "notes/day-27.md"],
        steps: [
          "确认故障一已修复且工作区干净后，学习者自行注入故障二：把 ActivityDetailView 中 const bookmarked=computed(() => bookmarkStore.isBookmarked(activityId)) 替换成 const bookmarked=ref(bookmarkStore.isBookmarked(activityId))，并补 ref 导入；其余代码不动。",
          "学习者在个人中心取消 a001 后返回详情，复现仍显示已收藏。",
          "移除本地副本，恢复直接读取 bookmarkStore/computed。",
          "按清单回归：登录、刷新、筛选、URL、详情、收藏、报名、个人中心取消、错误重试、退出、越权。",
        ],
        expected: ["详情重新随 store 更新。", "回归清单每项有通过证据。"],
        tests: ["npm run type-check", "npm run build", "完整回归清单", "Console 无红色错误"],
      },
      {
        title: "旧算法与提交",
        duration: 40,
        files: ["algorithms/day27-review.ts", "algorithms/day27-review.test.ts", "notes/day-27.md"],
        steps: ["股票题与最大子数组二选一从空白重写，另一题只口述状态。", "把所选题的两个旧用例写入 Vitest。", "提交 fix: stabilize student journey。"],
        expected: ["能说出本次比首次少看了什么提示。"],
        tests: ["npm run test:run -- algorithms/day27-review.test.ts", "重写题通过两个样例", "记录时间和 AI 等级"],
      },
    ],
    optional: ["无；若提前完成，只重复回归，不增加新功能。"],
    review: {
      route: "/activities?q=fast",
      steps: ["检查两个故障的复现记录。", "现场 slow→fast。", "个人中心取消收藏后返回详情。", "临时将 a001 的报名截止时间设为过去，要求定位应修改的类型、派生逻辑和 UI。"],
      expected: ["竞态与状态副本根因清楚。", "能说出截止状态至少影响哪些文件，不要求 5 分钟内写完。"],
    },
  },

  28: {
    start: {
      dir: "campus-growth-hub",
      commands: ["git status", "npm run type-check", "npm run test:run", "npm run build"],
      open: ["docs/student-regression.md", "docs/task-board.md", "README.md", "src/router/index.ts", "src/stores/auth.ts", "src/api/request.ts", "src/composables/useActivityQuery.ts"],
      before: ["轻量日总学习 150 分钟，不打开新课。", "先独立完成页面内代码走查和全部自测，再开始页面底部的 30 分钟统一审查；学习者任务结束后不加时。"],
    },
    tasks: [
      {
        title: "回看证据并选一个无 AI 复现项",
        duration: 40,
        files: ["notes/day-28.md", "docs/student-regression.md"],
        steps: ["按 Git 顺序写本周每个提交的一句话成果。", "统计 A-E 与通过状态，只选一个 D/E 项。", "写三条已掌握证据和一个最常见困难。"],
        expected: ["复盘同时包含进步与风险。"],
        tests: ["每条证据能指向提交、页面或错误记录"],
      },
      {
        title: "从空白完成一个可验收的小改动",
        duration: 50,
        files: ["src/types/activity.ts", "src/mocks/activities.ts", "src/utils/activityAvailability.ts", "src/utils/activityAvailability.test.ts", "src/views/ActivityDetailView.vue", "src/components/ActivityCard.vue"],
        steps: [
          "先在 Activity 增加必填 deadline:string。给全部 15 条 fixture 补 ISO 8601 +08:00 值：a004='2026-07-31T23:59:59+08:00'；a001、a002 及其余活动统一使用晚于 2026-08-01 的日期，禁止只给 a004 增字段。",
          "定义 getActivityAvailability(activity, now)，返回 open/full/expired；判断优先级固定为 deadline<=now 得 expired，其次 enrolledCount>=capacity 得 full，否则 open。",
          "在 activityAvailability.test.ts 使用固定 now=new Date('2026-08-01T00:00:00+08:00')，测试 a001/open、a002/full、a004/expired；不得在测试中直接使用 new Date() 当前时间。",
          "卡片显示已满或已截止，详情在 full/expired 时禁用报名；open 时可报名。",
          "先运行三个函数用例，再接 UI；不看旧业务判断代码。",
        ],
        expected: ["a001 可报名、a002 已满、a004 已截止。"],
        tests: ["npm run type-check", "npm run test:run -- src/utils/activityAvailability.test.ts", "打开 a001、a002、a004 三个详情页检查按钮"],
      },
      {
        title: "按固定脚本演示并冻结三个改进项",
        duration: 60,
        files: ["docs/task-board.md", "notes/day-28.md", "README.md"],
        steps: [
          "演示：学生登录→筛选→刷新→详情→收藏→报名→个人中心→取消→退出→学生越权。",
          "自查 router/index.ts、stores/auth.ts、api/request.ts、useActivityQuery.ts：职责、重复状态、错误态、any/断言。",
          "task-board 只保留 3 个下一阶段改进项，每项写优先级、文件、预计分钟、完成标准；其余移入 Backlog。",
          "随机重做一道旧题只口述或写伪代码，不再追求新题。",
        ],
        expected: ["完整演示无阻塞。", "三个改进项均可在半天内完成。"],
        tests: ["npm run build", "完整演示清单全部通过", "task-board Doing 不超过1项"],
      },
    ],
    optional: ["无；剩余时间用于休息。"],
    review: {
      route: "/activities",
      steps: ["检查者按完整学生流程操作。", "随机抽 router、auth store、request、query composable 各一处让学习者说明。", "检查 a004 已截止规则。", "审核 task-board 三个改进项。"],
      expected: ["能独立演示和解释主要数据流。", "a001/open、a002/full、a004/expired 表现正确。", "后续范围只保留三项，不因验收临时扩张。"],
    },
  },
};
